// This file is hand-maintained. It is NOT generated by protoc-gen-connect-go.
//
// The vendored decide proto is namespaced (arcjet.sdk.decide.v2) with a
// distinct descriptor path so its protobuf global-registry identity cannot
// collide with Arcjet's canonical decide proto when both are linked into the
// same Go binary (see arcjet/arcjet#8213 / ENG-852). Generating the Connect
// transport from the namespaced proto would emit the wrong wire route
// (/arcjet.sdk.decide.v2.DecideService/...) and bind the codec schema to the
// namespaced descriptor. The wire route is fixed by the wire contract and
// shared by every Arcjet SDK, so it is pinned here by hand against the
// canonical procedure names instead. The Connect codec marshals via each
// message's own ProtoReflect descriptor, so no schema/global registry is
// needed for these registry-free (no Any) messages.

package decidev2connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"

	v2 "github.com/arcjet/arcjet-go/internal/proto/decide/v2"
)

// This is a compile-time assertion to ensure that this file and the connect
// package are compatible.
const _ = connect.IsAtLeastVersion1_13_0

// DecideServiceName is the fully-qualified name of the DecideService service.
const DecideServiceName = "proto.decide.v2.DecideService"

// DecideServiceGuardProcedure is the canonical, fully-qualified wire route of
// the Guard RPC. It intentionally uses the canonical (proto.decide.v2) package,
// not the vendored proto's namespaced package — see the file comment.
const DecideServiceGuardProcedure = "/proto.decide.v2.DecideService/Guard"

// DecideServiceClient is a client for the proto.decide.v2.DecideService service.
type DecideServiceClient interface {
	// Evaluate a set of guard rules and return a decision.
	Guard(context.Context, *connect.Request[v2.GuardRequest]) (*connect.Response[v2.GuardResponse], error)
}

// NewDecideServiceClient constructs a client for the proto.decide.v2.DecideService service.
//
// The URL supplied here should be the base URL for the Connect or gRPC server
// (for example, http://api.acme.com or https://acme.com/grpc).
func NewDecideServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DecideServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &decideServiceClient{
		guard: connect.NewClient[v2.GuardRequest, v2.GuardResponse](
			httpClient,
			baseURL+DecideServiceGuardProcedure,
			opts...,
		),
	}
}

// decideServiceClient implements DecideServiceClient.
type decideServiceClient struct {
	guard *connect.Client[v2.GuardRequest, v2.GuardResponse]
}

// Guard calls proto.decide.v2.DecideService.Guard.
func (c *decideServiceClient) Guard(ctx context.Context, req *connect.Request[v2.GuardRequest]) (*connect.Response[v2.GuardResponse], error) {
	return c.guard.CallUnary(ctx, req)
}

// DecideServiceHandler is an implementation of the proto.decide.v2.DecideService service.
type DecideServiceHandler interface {
	// Evaluate a set of guard rules and return a decision.
	Guard(context.Context, *connect.Request[v2.GuardRequest]) (*connect.Response[v2.GuardResponse], error)
}

// NewDecideServiceHandler builds an HTTP handler from the service implementation.
// It returns the path on which to mount the handler and the handler itself.
func NewDecideServiceHandler(svc DecideServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	decideServiceGuardHandler := connect.NewUnaryHandler(
		DecideServiceGuardProcedure,
		svc.Guard,
		opts...,
	)
	return "/proto.decide.v2.DecideService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DecideServiceGuardProcedure:
			decideServiceGuardHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDecideServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDecideServiceHandler struct{}

func (UnimplementedDecideServiceHandler) Guard(context.Context, *connect.Request[v2.GuardRequest]) (*connect.Response[v2.GuardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.decide.v2.DecideService.Guard is not implemented"))
}
