// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/decide/v2/decide.proto

package decidev2connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2 "github.com/arcjet/arcjet-go/internal/proto/decide/v2"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DecideServiceName is the fully-qualified name of the DecideService service.
	DecideServiceName = "proto.decide.v2.DecideService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DecideServiceGuardProcedure is the fully-qualified name of the DecideService's Guard RPC.
	DecideServiceGuardProcedure = "/proto.decide.v2.DecideService/Guard"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	decideServiceServiceDescriptor     = v2.File_proto_decide_v2_decide_proto.Services().ByName("DecideService")
	decideServiceGuardMethodDescriptor = decideServiceServiceDescriptor.Methods().ByName("Guard")
)

// DecideServiceClient is a client for the proto.decide.v2.DecideService service.
type DecideServiceClient interface {
	// Evaluate a set of guard rules and return a decision.
	Guard(context.Context, *connect.Request[v2.GuardRequest]) (*connect.Response[v2.GuardResponse], error)
}

// NewDecideServiceClient constructs a client for the proto.decide.v2.DecideService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDecideServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DecideServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &decideServiceClient{
		guard: connect.NewClient[v2.GuardRequest, v2.GuardResponse](
			httpClient,
			baseURL+DecideServiceGuardProcedure,
			connect.WithSchema(decideServiceGuardMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// decideServiceClient implements DecideServiceClient.
type decideServiceClient struct {
	guard *connect.Client[v2.GuardRequest, v2.GuardResponse]
}

// Guard calls proto.decide.v2.DecideService.Guard.
func (c *decideServiceClient) Guard(ctx context.Context, req *connect.Request[v2.GuardRequest]) (*connect.Response[v2.GuardResponse], error) {
	return c.guard.CallUnary(ctx, req)
}

// DecideServiceHandler is an implementation of the proto.decide.v2.DecideService service.
type DecideServiceHandler interface {
	// Evaluate a set of guard rules and return a decision.
	Guard(context.Context, *connect.Request[v2.GuardRequest]) (*connect.Response[v2.GuardResponse], error)
}

// NewDecideServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDecideServiceHandler(svc DecideServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	decideServiceGuardHandler := connect.NewUnaryHandler(
		DecideServiceGuardProcedure,
		svc.Guard,
		connect.WithSchema(decideServiceGuardMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/proto.decide.v2.DecideService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DecideServiceGuardProcedure:
			decideServiceGuardHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDecideServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDecideServiceHandler struct{}

func (UnimplementedDecideServiceHandler) Guard(context.Context, *connect.Request[v2.GuardRequest]) (*connect.Response[v2.GuardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.decide.v2.DecideService.Guard is not implemented"))
}
