// Code generated by arcjet-gravity; DO NOT EDIT.

package jsreq

import "context"
import "errors"
import "github.com/tetratelabs/wazero"
import "github.com/tetratelabs/wazero/api"

import _ "embed"

//go:embed js_req.wasm
var wasmFileJsReq []byte

type IJsReqEmailValidatorOverrides interface {
	IsFreeEmail(
		ctx context.Context,
		domain string,
	) EmailValidatorOverridesValidatorResponse
	IsDisposableEmail(
		ctx context.Context,
		domain string,
	) EmailValidatorOverridesValidatorResponse
	HasMxRecords(
		ctx context.Context,
		domain string,
	) EmailValidatorOverridesValidatorResponse
	HasGravatar(
		ctx context.Context,
		email string,
	) EmailValidatorOverridesValidatorResponse
}

type EmailValidatorOverridesValidatorResponse interface {
	isEmailValidatorOverridesValidatorResponse()
}

type emailValidatorOverridesValidatorResponse int

func (emailValidatorOverridesValidatorResponse) isEmailValidatorOverridesValidatorResponse() {}

const (
	Yes emailValidatorOverridesValidatorResponse = iota
	No emailValidatorOverridesValidatorResponse = iota
	Unknown emailValidatorOverridesValidatorResponse = iota
)

type IJsReqSensitiveInformationIdentifier interface {
	Detect(
		ctx context.Context,
		tokens []string,
	) []*SensitiveInfoEntity
}

type SensitiveInfoEntity interface {
	isSensitiveInfoEntity()
}

type SensitiveInfoEntityEmail struct {}

func (SensitiveInfoEntityEmail) isSensitiveInfoEntity() {}

type SensitiveInfoEntityPhoneNumber struct {}

func (SensitiveInfoEntityPhoneNumber) isSensitiveInfoEntity() {}

type SensitiveInfoEntityIpAddress struct {}

func (SensitiveInfoEntityIpAddress) isSensitiveInfoEntity() {}

type SensitiveInfoEntityCreditCardNumber struct {}

func (SensitiveInfoEntityCreditCardNumber) isSensitiveInfoEntity() {}

type SensitiveInfoEntityCustom struct {
	Value string
}

func (SensitiveInfoEntityCustom) isSensitiveInfoEntity() {}

type IJsReqVerifyBot interface {
	Verify(
		ctx context.Context,
		botId string,
		ip string,
	) VerifyBotValidatorResponse
}

type VerifyBotValidatorResponse interface {
	isVerifyBotValidatorResponse()
}

type verifyBotValidatorResponse int

func (verifyBotValidatorResponse) isVerifyBotValidatorResponse() {}

const (
	Verified verifyBotValidatorResponse = iota
	Spoofed verifyBotValidatorResponse = iota
	Unverifiable verifyBotValidatorResponse = iota
)

type IJsReqBotIdentifier interface {
	Detect(
		ctx context.Context,
		request string,
	) []BotEntity
}

type BotEntity = string

type IJsReqFilterOverrides interface {
	IpLookup(
		ctx context.Context,
		ip string,
	) *string
}

type EmailValidity interface {
	isEmailValidity()
}

type emailValidity int

func (emailValidity) isEmailValidity() {}

const (
	Valid emailValidity = iota
	Invalid emailValidity = iota
)

type EmailValidationResult struct {
	Validity EmailValidity
	Blocked []string
}

type AllowEmailValidationConfig struct {
	RequireTopLevelDomain bool
	AllowDomainLiteral bool
	Allow []string
}

type DenyEmailValidationConfig struct {
	RequireTopLevelDomain bool
	AllowDomainLiteral bool
	Deny []string
}

type EmailValidationConfig interface {
	isEmailValidationConfig()
}

func (AllowEmailValidationConfig) isEmailValidationConfig() {}

func (DenyEmailValidationConfig) isEmailValidationConfig() {}

type SensitiveInfoEntities interface {
	isSensitiveInfoEntities()
}

type SensitiveInfoEntitiesAllow struct {
	Value []SensitiveInfoEntity
}

func (SensitiveInfoEntitiesAllow) isSensitiveInfoEntities() {}

type SensitiveInfoEntitiesDeny struct {
	Value []SensitiveInfoEntity
}

func (SensitiveInfoEntitiesDeny) isSensitiveInfoEntities() {}

type SensitiveInfoConfig struct {
	Entities SensitiveInfoEntities
	ContextWindowSize *uint32
	SkipCustomDetect bool
}

type DetectedSensitiveInfoEntity struct {
	Start uint32
	End uint32
	IdentifiedType SensitiveInfoEntity
}

type SensitiveInfoResult struct {
	Allowed []DetectedSensitiveInfoEntity
	Denied []DetectedSensitiveInfoEntity
}

type AllowedBotConfig struct {
	Entities []BotEntity
	SkipCustomDetect bool
}

type DeniedBotConfig struct {
	Entities []BotEntity
	SkipCustomDetect bool
}

type BotConfig interface {
	isBotConfig()
}

func (AllowedBotConfig) isBotConfig() {}

func (DeniedBotConfig) isBotConfig() {}

type BotResult struct {
	Allowed []BotEntity
	Denied []BotEntity
	Verified bool
	Spoofed bool
}

type FilterResult struct {
	Allowed bool
	MatchedExpressions []string
	UndeterminedExpressions []string
}

type JsReqFactory struct {
	runtime wazero.Runtime
	module wazero.CompiledModule
}

func NewJsReqFactory(
	ctx context.Context,
	emailValidatorOverrides IJsReqEmailValidatorOverrides,
	sensitiveInformationIdentifier IJsReqSensitiveInformationIdentifier,
	verifyBot IJsReqVerifyBot,
	botIdentifier IJsReqBotIdentifier,
	filterOverrides IJsReqFilterOverrides,
) (*JsReqFactory, error) {
	wazeroRuntime := wazero.NewRuntime(ctx)

	_, err3 := wazeroRuntime.NewHostModuleBuilder("arcjet:js-req/bot-identifier").
	NewFunctionBuilder().
	WithFunc(func(
		ctx context.Context,
		mod api.Module,
		arg0 uint32,
		arg1 uint32,
		arg2 uint32,
	) {
		buf0, ok0 := mod.Memory().Read(arg0, arg1)
		if !ok0 {
			panic(errors.New("failed to read bytes from memory"))
		}
		str0 := string(buf0)
		value1 := botIdentifier.Detect(ctx, str0)
		vec3 := value1
		len3 := uint64(len(vec3))
		result3, err3 := mod.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len3 * 8)
		// The return type doesn't contain an error so we panic if one is encountered
		if err3 != nil {
			panic(err3)
		}
		ptr3 := result3[0]
		for idx := uint64(0); idx < len3; idx++ {
			e := vec3[idx]
			base := uint32(ptr3 + uint64(idx) * uint64(8))
			memory2 := mod.Memory()
			realloc2 := mod.ExportedFunction("cabi_realloc")
			ptr2, len2, err2 := writeString(ctx, e, memory2, realloc2)
			if err2 != nil {
				panic(err2)
			}
			mod.Memory().WriteUint32Le(base+4, uint32(len2))
			mod.Memory().WriteUint32Le(base+0, uint32(ptr2))
		}
		mod.Memory().WriteUint32Le(arg2+4, uint32(len3))
		mod.Memory().WriteUint32Le(arg2+0, uint32(ptr3))
	}).
	Export("detect").
	Instantiate(ctx)
	if err3 != nil {
		return nil, err3
	}
	_, err0 := wazeroRuntime.NewHostModuleBuilder("arcjet:js-req/email-validator-overrides").
	NewFunctionBuilder().
	WithFunc(func(
		ctx context.Context,
		mod api.Module,
		arg0 uint32,
		arg1 uint32,
	) uint32{
		buf0, ok0 := mod.Memory().Read(arg0, arg1)
		if !ok0 {
			panic(errors.New("failed to read bytes from memory"))
		}
		str0 := string(buf0)
		value1 := emailValidatorOverrides.IsFreeEmail(ctx, str0)
		var enum2 uint32
		switch value1 {
		case Yes:
			enum2 = 0
		case No:
			enum2 = 1
		case Unknown:
			enum2 = 2
		default:
			panic(errors.New("invalid enum type provided"))
		}
		return enum2
	}).
	Export("is-free-email").
	NewFunctionBuilder().
	WithFunc(func(
		ctx context.Context,
		mod api.Module,
		arg0 uint32,
		arg1 uint32,
	) uint32{
		buf0, ok0 := mod.Memory().Read(arg0, arg1)
		if !ok0 {
			panic(errors.New("failed to read bytes from memory"))
		}
		str0 := string(buf0)
		value1 := emailValidatorOverrides.IsDisposableEmail(ctx, str0)
		var enum2 uint32
		switch value1 {
		case Yes:
			enum2 = 0
		case No:
			enum2 = 1
		case Unknown:
			enum2 = 2
		default:
			panic(errors.New("invalid enum type provided"))
		}
		return enum2
	}).
	Export("is-disposable-email").
	NewFunctionBuilder().
	WithFunc(func(
		ctx context.Context,
		mod api.Module,
		arg0 uint32,
		arg1 uint32,
	) uint32{
		buf0, ok0 := mod.Memory().Read(arg0, arg1)
		if !ok0 {
			panic(errors.New("failed to read bytes from memory"))
		}
		str0 := string(buf0)
		value1 := emailValidatorOverrides.HasMxRecords(ctx, str0)
		var enum2 uint32
		switch value1 {
		case Yes:
			enum2 = 0
		case No:
			enum2 = 1
		case Unknown:
			enum2 = 2
		default:
			panic(errors.New("invalid enum type provided"))
		}
		return enum2
	}).
	Export("has-mx-records").
	NewFunctionBuilder().
	WithFunc(func(
		ctx context.Context,
		mod api.Module,
		arg0 uint32,
		arg1 uint32,
	) uint32{
		buf0, ok0 := mod.Memory().Read(arg0, arg1)
		if !ok0 {
			panic(errors.New("failed to read bytes from memory"))
		}
		str0 := string(buf0)
		value1 := emailValidatorOverrides.HasGravatar(ctx, str0)
		var enum2 uint32
		switch value1 {
		case Yes:
			enum2 = 0
		case No:
			enum2 = 1
		case Unknown:
			enum2 = 2
		default:
			panic(errors.New("invalid enum type provided"))
		}
		return enum2
	}).
	Export("has-gravatar").
	Instantiate(ctx)
	if err0 != nil {
		return nil, err0
	}
	_, err4 := wazeroRuntime.NewHostModuleBuilder("arcjet:js-req/filter-overrides").
	NewFunctionBuilder().
	WithFunc(func(
		ctx context.Context,
		mod api.Module,
		arg0 uint32,
		arg1 uint32,
		arg2 uint32,
	) {
		buf0, ok0 := mod.Memory().Read(arg0, arg1)
		if !ok0 {
			panic(errors.New("failed to read bytes from memory"))
		}
		str0 := string(buf0)
		value1 := filterOverrides.IpLookup(ctx, str0)
		if value1 == nil {
			mod.Memory().WriteByte(arg2+0, 0)
		} else {
			variantPayload := *value1
			mod.Memory().WriteByte(arg2+0, 1)
			memory2 := mod.Memory()
			realloc2 := mod.ExportedFunction("cabi_realloc")
			ptr2, len2, err2 := writeString(ctx, variantPayload, memory2, realloc2)
			if err2 != nil {
				panic(err2)
			}
			mod.Memory().WriteUint32Le(arg2+8, uint32(len2))
			mod.Memory().WriteUint32Le(arg2+4, uint32(ptr2))
		}
	}).
	Export("ip-lookup").
	Instantiate(ctx)
	if err4 != nil {
		return nil, err4
	}
	_, err1 := wazeroRuntime.NewHostModuleBuilder("arcjet:js-req/sensitive-information-identifier").
	NewFunctionBuilder().
	WithFunc(func(
		ctx context.Context,
		mod api.Module,
		arg0 uint32,
		arg1 uint32,
		arg2 uint32,
	) {
		base3 := arg0
		len3 := arg1
		result3 := make([]string, len3)
		for idx3 := uint32(0); idx3 < len3; idx3++ {
			base := base3 + idx3 * 8
			ptr0, ok0 := mod.Memory().ReadUint32Le(uint32(base + 0))
			// The return type doesn't contain an error so we panic if one is encountered
			if !ok0 {
				panic(errors.New("failed to read pointer from memory"))
			}
			len1, ok1 := mod.Memory().ReadUint32Le(uint32(base + 4))
			// The return type doesn't contain an error so we panic if one is encountered
			if !ok1 {
				panic(errors.New("failed to read length from memory"))
			}
			buf2, ok2 := mod.Memory().Read(ptr0, len1)
			if !ok2 {
				panic(errors.New("failed to read bytes from memory"))
			}
			str2 := string(buf2)
			result3[idx3] = str2
		}
		value4 := sensitiveInformationIdentifier.Detect(ctx, result3)
		vec8 := value4
		len8 := uint64(len(vec8))
		result8, err8 := mod.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len8 * 16)
		// The return type doesn't contain an error so we panic if one is encountered
		if err8 != nil {
			panic(err8)
		}
		ptr8 := result8[0]
		for idx := uint64(0); idx < len8; idx++ {
			e := vec8[idx]
			base := uint32(ptr8 + uint64(idx) * uint64(16))
			if e == nil {
				mod.Memory().WriteByte(base+0, 0)
			} else {
				variantPayload := *e
				mod.Memory().WriteByte(base+0, 1)
				switch case6 := variantPayload.(type) {
					case SensitiveInfoEntityEmail:
						_ = case6
						mod.Memory().WriteByte(base+4, 0)
					case SensitiveInfoEntityPhoneNumber:
						_ = case6
						mod.Memory().WriteByte(base+4, 1)
					case SensitiveInfoEntityIpAddress:
						_ = case6
						mod.Memory().WriteByte(base+4, 2)
					case SensitiveInfoEntityCreditCardNumber:
						_ = case6
						mod.Memory().WriteByte(base+4, 3)
					case SensitiveInfoEntityCustom:
						variantPayload := case6.Value
						mod.Memory().WriteByte(base+4, 4)
						memory5 := mod.Memory()
						realloc5 := mod.ExportedFunction("cabi_realloc")
						ptr5, len5, err5 := writeString(ctx, variantPayload, memory5, realloc5)
						if err5 != nil {
							panic(err5)
						}
						mod.Memory().WriteUint32Le(base+12, uint32(len5))
						mod.Memory().WriteUint32Le(base+8, uint32(ptr5))
					default:
						// The return type doesn't contain an error so we panic if one is encountered
						panic(errors.New("invalid variant type provided"))
				}
			}
		}
		mod.Memory().WriteUint32Le(arg2+4, uint32(len8))
		mod.Memory().WriteUint32Le(arg2+0, uint32(ptr8))
	}).
	Export("detect").
	Instantiate(ctx)
	if err1 != nil {
		return nil, err1
	}
	_, err2 := wazeroRuntime.NewHostModuleBuilder("arcjet:js-req/verify-bot").
	NewFunctionBuilder().
	WithFunc(func(
		ctx context.Context,
		mod api.Module,
		arg0 uint32,
		arg1 uint32,
		arg2 uint32,
		arg3 uint32,
	) uint32{
		buf0, ok0 := mod.Memory().Read(arg0, arg1)
		if !ok0 {
			panic(errors.New("failed to read bytes from memory"))
		}
		str0 := string(buf0)
		buf1, ok1 := mod.Memory().Read(arg2, arg3)
		if !ok1 {
			panic(errors.New("failed to read bytes from memory"))
		}
		str1 := string(buf1)
		value2 := verifyBot.Verify(ctx, str0, str1)
		var enum3 uint32
		switch value2 {
		case Verified:
			enum3 = 0
		case Spoofed:
			enum3 = 1
		case Unverifiable:
			enum3 = 2
		default:
			panic(errors.New("invalid enum type provided"))
		}
		return enum3
	}).
	Export("verify").
	Instantiate(ctx)
	if err2 != nil {
		return nil, err2
	}

	// Compiling the module takes a LONG time, so we want to do it once and hold
	// onto it with the Runtime
	module, err := wazeroRuntime.CompileModule(ctx, wasmFileJsReq)
	if err != nil {
		return nil, err
	}
	return &JsReqFactory{
		runtime: wazeroRuntime,
		module: module,
	}, nil
}

func (f *JsReqFactory) Instantiate(ctx context.Context) (*JsReqInstance, error) {
	if module, err := f.runtime.InstantiateModule(ctx, f.module, wazero.NewModuleConfig()); err != nil {
		return nil, err
	} else {
		return &JsReqInstance{module}, nil
	}
}

func (f *JsReqFactory) Close(ctx context.Context) {
	f.runtime.Close(ctx)
}

type JsReqInstance struct {
	module api.Module
}

func (i *JsReqInstance) Close(ctx context.Context) error {
	if err := i.module.Close(ctx); err != nil {
		return err
	}

	return nil
}

// writeString will put a Go string into the Wasm memory following the Component
// Model calling conventions, such as allocating memory with the realloc function
func writeString(
	ctx context.Context,
	s string,
	memory api.Memory,
	realloc api.Function,
) (uint64, uint64, error) {
	if len(s) == 0 {
		return 1, 0, nil
	}

	results, err := realloc.Call(ctx, 0, 0, 1, uint64(len(s)))
	if err != nil {
		return 1, 0, err
	}
	ptr := results[0]
	ok := memory.Write(uint32(ptr), []byte(s))
	if !ok {
		return 1, 0, errors.New("failed to write string to wasm memory")
	}
	return uint64(ptr), uint64(len(s)), nil
}

func (i *JsReqInstance) DetectBot(
	ctx context.Context,
	request string,
	options interface{},
) (BotResult, error) {
	arg0 := request
	arg1 := options
	memory0 := i.module.Memory()
	realloc0 := i.module.ExportedFunction("cabi_realloc")
	ptr0, len0, err0 := writeString(ctx, arg0, memory0, realloc0)
	if err0 != nil {
		var default0 BotResult
		return default0, err0
	}
	var variant9_0 uint32
	var variant9_1 uint64
	var variant9_2 uint64
	var variant9_3 uint32
	switch variantPayload := arg1.(type) {
		case AllowedBotConfig:
			entities1 := variantPayload.Entities
			skipCustomDetect1 := variantPayload.SkipCustomDetect
			vec3 := entities1
			len3 := uint64(len(vec3))
			result3, err3 := i.module.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len3 * 8)
			if err3 != nil {
				var default3 BotResult
				return default3, err3
			}
			ptr3 := result3[0]
			for idx := uint64(0); idx < len3; idx++ {
				e := vec3[idx]
				base := uint32(ptr3 + uint64(idx) * uint64(8))
				memory2 := i.module.Memory()
				realloc2 := i.module.ExportedFunction("cabi_realloc")
				ptr2, len2, err2 := writeString(ctx, e, memory2, realloc2)
				if err2 != nil {
					var default2 BotResult
					return default2, err2
				}
				i.module.Memory().WriteUint32Le(base+4, uint32(len2))
				i.module.Memory().WriteUint32Le(base+0, uint32(ptr2))
			}
			var value4 uint32
			if skipCustomDetect1 {
				value4 = 1
			} else {
				value4 = 0
			}
			variant9_0 = 0
			variant9_1 = ptr3
			variant9_2 = len3
			variant9_3 = value4
		case DeniedBotConfig:
			entities5 := variantPayload.Entities
			skipCustomDetect5 := variantPayload.SkipCustomDetect
			vec7 := entities5
			len7 := uint64(len(vec7))
			result7, err7 := i.module.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len7 * 8)
			if err7 != nil {
				var default7 BotResult
				return default7, err7
			}
			ptr7 := result7[0]
			for idx := uint64(0); idx < len7; idx++ {
				e := vec7[idx]
				base := uint32(ptr7 + uint64(idx) * uint64(8))
				memory6 := i.module.Memory()
				realloc6 := i.module.ExportedFunction("cabi_realloc")
				ptr6, len6, err6 := writeString(ctx, e, memory6, realloc6)
				if err6 != nil {
					var default6 BotResult
					return default6, err6
				}
				i.module.Memory().WriteUint32Le(base+4, uint32(len6))
				i.module.Memory().WriteUint32Le(base+0, uint32(ptr6))
			}
			var value8 uint32
			if skipCustomDetect5 {
				value8 = 1
			} else {
				value8 = 0
			}
			variant9_0 = 1
			variant9_1 = ptr7
			variant9_2 = len7
			variant9_3 = value8
		default:
			var default9 BotResult
			return default9, errors.New("invalid variant type provided")
	}
	raw10, err10 := i.module.ExportedFunction("detect-bot").Call(ctx, uint64(ptr0), uint64(len0), uint64(variant9_0), uint64(variant9_1), uint64(variant9_2), uint64(variant9_3))
	if err10 != nil {
		var default10 BotResult
		return default10, err10
	}

	// The cleanup via `cabi_post_*` cleans up the memory in the guest. By
	// deferring this, we ensure that no memory is corrupted before the function
	// is done accessing it.
	defer func() {
		if postFn := i.module.ExportedFunction("cabi_post_detect-bot"); postFn != nil {
			if _, err := postFn.Call(ctx, raw10...); err != nil {
				// If we get an error during cleanup, something really bad is
				// going on, so we panic. Also, you can't return the error from
				// the `defer`
				panic(errors.New("failed to cleanup"))
			}
		}
	}()

	results10 := raw10[0]
	value11, ok11 := i.module.Memory().ReadByte(uint32(results10 + 0))
	if !ok11 {
		var default11 BotResult
		return default11, errors.New("failed to read byte from memory")
	}
	var value32 BotResult
	var err32 error
	switch value11 {
	case 0:
		ptr12, ok12 := i.module.Memory().ReadUint32Le(uint32(results10 + 4))
		if !ok12 {
			var default12 BotResult
			return default12, errors.New("failed to read pointer from memory")
		}
		len13, ok13 := i.module.Memory().ReadUint32Le(uint32(results10 + 8))
		if !ok13 {
			var default13 BotResult
			return default13, errors.New("failed to read length from memory")
		}
		base17 := ptr12
		len17 := len13
		result17 := make([]BotEntity, len17)
		for idx17 := uint32(0); idx17 < len17; idx17++ {
			base := base17 + idx17 * 8
			ptr14, ok14 := i.module.Memory().ReadUint32Le(uint32(base + 0))
			if !ok14 {
				var default14 BotResult
				return default14, errors.New("failed to read pointer from memory")
			}
			len15, ok15 := i.module.Memory().ReadUint32Le(uint32(base + 4))
			if !ok15 {
				var default15 BotResult
				return default15, errors.New("failed to read length from memory")
			}
			buf16, ok16 := i.module.Memory().Read(ptr14, len15)
			if !ok16 {
				var default16 BotResult
				return default16, errors.New("failed to read bytes from memory")
			}
			str16 := string(buf16)
			result17[idx17] = str16
		}
		ptr18, ok18 := i.module.Memory().ReadUint32Le(uint32(results10 + 12))
		if !ok18 {
			var default18 BotResult
			return default18, errors.New("failed to read pointer from memory")
		}
		len19, ok19 := i.module.Memory().ReadUint32Le(uint32(results10 + 16))
		if !ok19 {
			var default19 BotResult
			return default19, errors.New("failed to read length from memory")
		}
		base23 := ptr18
		len23 := len19
		result23 := make([]BotEntity, len23)
		for idx23 := uint32(0); idx23 < len23; idx23++ {
			base := base23 + idx23 * 8
			ptr20, ok20 := i.module.Memory().ReadUint32Le(uint32(base + 0))
			if !ok20 {
				var default20 BotResult
				return default20, errors.New("failed to read pointer from memory")
			}
			len21, ok21 := i.module.Memory().ReadUint32Le(uint32(base + 4))
			if !ok21 {
				var default21 BotResult
				return default21, errors.New("failed to read length from memory")
			}
			buf22, ok22 := i.module.Memory().Read(ptr20, len21)
			if !ok22 {
				var default22 BotResult
				return default22, errors.New("failed to read bytes from memory")
			}
			str22 := string(buf22)
			result23[idx23] = str22
		}
		value24, ok24 := i.module.Memory().ReadByte(uint32(results10 + 20))
		if !ok24 {
			var default24 BotResult
			return default24, errors.New("failed to read byte from memory")
		}
		value25 := value24 != 0
		value26, ok26 := i.module.Memory().ReadByte(uint32(results10 + 21))
		if !ok26 {
			var default26 BotResult
			return default26, errors.New("failed to read byte from memory")
		}
		value27 := value26 != 0
		value28 := BotResult{
			Allowed: result17,
			Denied: result23,
			Verified: value25,
			Spoofed: value27,
		}
		value32 = value28
	case 1:
		ptr29, ok29 := i.module.Memory().ReadUint32Le(uint32(results10 + 4))
		if !ok29 {
			var default29 BotResult
			return default29, errors.New("failed to read pointer from memory")
		}
		len30, ok30 := i.module.Memory().ReadUint32Le(uint32(results10 + 8))
		if !ok30 {
			var default30 BotResult
			return default30, errors.New("failed to read length from memory")
		}
		buf31, ok31 := i.module.Memory().Read(ptr29, len30)
		if !ok31 {
			var default31 BotResult
			return default31, errors.New("failed to read bytes from memory")
		}
		str31 := string(buf31)
		err32 = errors.New(str31)
	default:
		err32 = errors.New("invalid variant discriminant for expected")
	}
	return value32, err32
}

func (i *JsReqInstance) MatchFilters(
	ctx context.Context,
	request string,
	localFields string,
	expressions []string,
	allowIfMatch bool,
) (FilterResult, error) {
	arg0 := request
	arg1 := localFields
	arg2 := expressions
	arg3 := allowIfMatch
	memory0 := i.module.Memory()
	realloc0 := i.module.ExportedFunction("cabi_realloc")
	ptr0, len0, err0 := writeString(ctx, arg0, memory0, realloc0)
	if err0 != nil {
		var default0 FilterResult
		return default0, err0
	}
	memory1 := i.module.Memory()
	realloc1 := i.module.ExportedFunction("cabi_realloc")
	ptr1, len1, err1 := writeString(ctx, arg1, memory1, realloc1)
	if err1 != nil {
		var default1 FilterResult
		return default1, err1
	}
	vec3 := arg2
	len3 := uint64(len(vec3))
	result3, err3 := i.module.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len3 * 8)
	if err3 != nil {
		var default3 FilterResult
		return default3, err3
	}
	ptr3 := result3[0]
	for idx := uint64(0); idx < len3; idx++ {
		e := vec3[idx]
		base := uint32(ptr3 + uint64(idx) * uint64(8))
		memory2 := i.module.Memory()
		realloc2 := i.module.ExportedFunction("cabi_realloc")
		ptr2, len2, err2 := writeString(ctx, e, memory2, realloc2)
		if err2 != nil {
			var default2 FilterResult
			return default2, err2
		}
		i.module.Memory().WriteUint32Le(base+4, uint32(len2))
		i.module.Memory().WriteUint32Le(base+0, uint32(ptr2))
	}
	var value4 uint32
	if arg3 {
		value4 = 1
	} else {
		value4 = 0
	}
	raw5, err5 := i.module.ExportedFunction("match-filters").Call(ctx, uint64(ptr0), uint64(len0), uint64(ptr1), uint64(len1), uint64(ptr3), uint64(len3), uint64(value4))
	if err5 != nil {
		var default5 FilterResult
		return default5, err5
	}

	// The cleanup via `cabi_post_*` cleans up the memory in the guest. By
	// deferring this, we ensure that no memory is corrupted before the function
	// is done accessing it.
	defer func() {
		if postFn := i.module.ExportedFunction("cabi_post_match-filters"); postFn != nil {
			if _, err := postFn.Call(ctx, raw5...); err != nil {
				// If we get an error during cleanup, something really bad is
				// going on, so we panic. Also, you can't return the error from
				// the `defer`
				panic(errors.New("failed to cleanup"))
			}
		}
	}()

	results5 := raw5[0]
	value6, ok6 := i.module.Memory().ReadByte(uint32(results5 + 0))
	if !ok6 {
		var default6 FilterResult
		return default6, errors.New("failed to read byte from memory")
	}
	var value25 FilterResult
	var err25 error
	switch value6 {
	case 0:
		value7, ok7 := i.module.Memory().ReadByte(uint32(results5 + 4))
		if !ok7 {
			var default7 FilterResult
			return default7, errors.New("failed to read byte from memory")
		}
		value8 := value7 != 0
		ptr9, ok9 := i.module.Memory().ReadUint32Le(uint32(results5 + 8))
		if !ok9 {
			var default9 FilterResult
			return default9, errors.New("failed to read pointer from memory")
		}
		len10, ok10 := i.module.Memory().ReadUint32Le(uint32(results5 + 12))
		if !ok10 {
			var default10 FilterResult
			return default10, errors.New("failed to read length from memory")
		}
		base14 := ptr9
		len14 := len10
		result14 := make([]string, len14)
		for idx14 := uint32(0); idx14 < len14; idx14++ {
			base := base14 + idx14 * 8
			ptr11, ok11 := i.module.Memory().ReadUint32Le(uint32(base + 0))
			if !ok11 {
				var default11 FilterResult
				return default11, errors.New("failed to read pointer from memory")
			}
			len12, ok12 := i.module.Memory().ReadUint32Le(uint32(base + 4))
			if !ok12 {
				var default12 FilterResult
				return default12, errors.New("failed to read length from memory")
			}
			buf13, ok13 := i.module.Memory().Read(ptr11, len12)
			if !ok13 {
				var default13 FilterResult
				return default13, errors.New("failed to read bytes from memory")
			}
			str13 := string(buf13)
			result14[idx14] = str13
		}
		ptr15, ok15 := i.module.Memory().ReadUint32Le(uint32(results5 + 16))
		if !ok15 {
			var default15 FilterResult
			return default15, errors.New("failed to read pointer from memory")
		}
		len16, ok16 := i.module.Memory().ReadUint32Le(uint32(results5 + 20))
		if !ok16 {
			var default16 FilterResult
			return default16, errors.New("failed to read length from memory")
		}
		base20 := ptr15
		len20 := len16
		result20 := make([]string, len20)
		for idx20 := uint32(0); idx20 < len20; idx20++ {
			base := base20 + idx20 * 8
			ptr17, ok17 := i.module.Memory().ReadUint32Le(uint32(base + 0))
			if !ok17 {
				var default17 FilterResult
				return default17, errors.New("failed to read pointer from memory")
			}
			len18, ok18 := i.module.Memory().ReadUint32Le(uint32(base + 4))
			if !ok18 {
				var default18 FilterResult
				return default18, errors.New("failed to read length from memory")
			}
			buf19, ok19 := i.module.Memory().Read(ptr17, len18)
			if !ok19 {
				var default19 FilterResult
				return default19, errors.New("failed to read bytes from memory")
			}
			str19 := string(buf19)
			result20[idx20] = str19
		}
		value21 := FilterResult{
			Allowed: value8,
			MatchedExpressions: result14,
			UndeterminedExpressions: result20,
		}
		value25 = value21
	case 1:
		ptr22, ok22 := i.module.Memory().ReadUint32Le(uint32(results5 + 4))
		if !ok22 {
			var default22 FilterResult
			return default22, errors.New("failed to read pointer from memory")
		}
		len23, ok23 := i.module.Memory().ReadUint32Le(uint32(results5 + 8))
		if !ok23 {
			var default23 FilterResult
			return default23, errors.New("failed to read length from memory")
		}
		buf24, ok24 := i.module.Memory().Read(ptr22, len23)
		if !ok24 {
			var default24 FilterResult
			return default24, errors.New("failed to read bytes from memory")
		}
		str24 := string(buf24)
		err25 = errors.New(str24)
	default:
		err25 = errors.New("invalid variant discriminant for expected")
	}
	return value25, err25
}

func (i *JsReqInstance) GenerateFingerprint(
	ctx context.Context,
	request string,
	characteristics []string,
) (string, error) {
	arg0 := request
	arg1 := characteristics
	memory0 := i.module.Memory()
	realloc0 := i.module.ExportedFunction("cabi_realloc")
	ptr0, len0, err0 := writeString(ctx, arg0, memory0, realloc0)
	if err0 != nil {
		var default0 string
		return default0, err0
	}
	vec2 := arg1
	len2 := uint64(len(vec2))
	result2, err2 := i.module.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len2 * 8)
	if err2 != nil {
		var default2 string
		return default2, err2
	}
	ptr2 := result2[0]
	for idx := uint64(0); idx < len2; idx++ {
		e := vec2[idx]
		base := uint32(ptr2 + uint64(idx) * uint64(8))
		memory1 := i.module.Memory()
		realloc1 := i.module.ExportedFunction("cabi_realloc")
		ptr1, len1, err1 := writeString(ctx, e, memory1, realloc1)
		if err1 != nil {
			var default1 string
			return default1, err1
		}
		i.module.Memory().WriteUint32Le(base+4, uint32(len1))
		i.module.Memory().WriteUint32Le(base+0, uint32(ptr1))
	}
	raw3, err3 := i.module.ExportedFunction("generate-fingerprint").Call(ctx, uint64(ptr0), uint64(len0), uint64(ptr2), uint64(len2))
	if err3 != nil {
		var default3 string
		return default3, err3
	}

	// The cleanup via `cabi_post_*` cleans up the memory in the guest. By
	// deferring this, we ensure that no memory is corrupted before the function
	// is done accessing it.
	defer func() {
		if postFn := i.module.ExportedFunction("cabi_post_generate-fingerprint"); postFn != nil {
			if _, err := postFn.Call(ctx, raw3...); err != nil {
				// If we get an error during cleanup, something really bad is
				// going on, so we panic. Also, you can't return the error from
				// the `defer`
				panic(errors.New("failed to cleanup"))
			}
		}
	}()

	results3 := raw3[0]
	value4, ok4 := i.module.Memory().ReadByte(uint32(results3 + 0))
	if !ok4 {
		var default4 string
		return default4, errors.New("failed to read byte from memory")
	}
	var value11 string
	var err11 error
	switch value4 {
	case 0:
		ptr5, ok5 := i.module.Memory().ReadUint32Le(uint32(results3 + 4))
		if !ok5 {
			var default5 string
			return default5, errors.New("failed to read pointer from memory")
		}
		len6, ok6 := i.module.Memory().ReadUint32Le(uint32(results3 + 8))
		if !ok6 {
			var default6 string
			return default6, errors.New("failed to read length from memory")
		}
		buf7, ok7 := i.module.Memory().Read(ptr5, len6)
		if !ok7 {
			var default7 string
			return default7, errors.New("failed to read bytes from memory")
		}
		str7 := string(buf7)
		value11 = str7
	case 1:
		ptr8, ok8 := i.module.Memory().ReadUint32Le(uint32(results3 + 4))
		if !ok8 {
			var default8 string
			return default8, errors.New("failed to read pointer from memory")
		}
		len9, ok9 := i.module.Memory().ReadUint32Le(uint32(results3 + 8))
		if !ok9 {
			var default9 string
			return default9, errors.New("failed to read length from memory")
		}
		buf10, ok10 := i.module.Memory().Read(ptr8, len9)
		if !ok10 {
			var default10 string
			return default10, errors.New("failed to read bytes from memory")
		}
		str10 := string(buf10)
		err11 = errors.New(str10)
	default:
		err11 = errors.New("invalid variant discriminant for expected")
	}
	return value11, err11
}

func (i *JsReqInstance) ValidateCharacteristics(
	ctx context.Context,
	request string,
	characteristics []string,
) error {
	arg0 := request
	arg1 := characteristics
	memory0 := i.module.Memory()
	realloc0 := i.module.ExportedFunction("cabi_realloc")
	ptr0, len0, err0 := writeString(ctx, arg0, memory0, realloc0)
	if err0 != nil {
		return err0
	}
	vec2 := arg1
	len2 := uint64(len(vec2))
	result2, err2 := i.module.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len2 * 8)
	if err2 != nil {
		return err2
	}
	ptr2 := result2[0]
	for idx := uint64(0); idx < len2; idx++ {
		e := vec2[idx]
		base := uint32(ptr2 + uint64(idx) * uint64(8))
		memory1 := i.module.Memory()
		realloc1 := i.module.ExportedFunction("cabi_realloc")
		ptr1, len1, err1 := writeString(ctx, e, memory1, realloc1)
		if err1 != nil {
			return err1
		}
		i.module.Memory().WriteUint32Le(base+4, uint32(len1))
		i.module.Memory().WriteUint32Le(base+0, uint32(ptr1))
	}
	raw3, err3 := i.module.ExportedFunction("validate-characteristics").Call(ctx, uint64(ptr0), uint64(len0), uint64(ptr2), uint64(len2))
	if err3 != nil {
		return err3
	}

	// The cleanup via `cabi_post_*` cleans up the memory in the guest. By
	// deferring this, we ensure that no memory is corrupted before the function
	// is done accessing it.
	defer func() {
		if postFn := i.module.ExportedFunction("cabi_post_validate-characteristics"); postFn != nil {
			if _, err := postFn.Call(ctx, raw3...); err != nil {
				// If we get an error during cleanup, something really bad is
				// going on, so we panic. Also, you can't return the error from
				// the `defer`
				panic(errors.New("failed to cleanup"))
			}
		}
	}()

	results3 := raw3[0]
	value4, ok4 := i.module.Memory().ReadByte(uint32(results3 + 0))
	if !ok4 {
		return errors.New("failed to read byte from memory")
	}
	var err8 error
	switch value4 {
	case 0:case 1:
		ptr5, ok5 := i.module.Memory().ReadUint32Le(uint32(results3 + 4))
		if !ok5 {
			return errors.New("failed to read pointer from memory")
		}
		len6, ok6 := i.module.Memory().ReadUint32Le(uint32(results3 + 8))
		if !ok6 {
			return errors.New("failed to read length from memory")
		}
		buf7, ok7 := i.module.Memory().Read(ptr5, len6)
		if !ok7 {
			return errors.New("failed to read bytes from memory")
		}
		str7 := string(buf7)
		err8 = errors.New(str7)
	default:
		err8 = errors.New("invalid variant discriminant for expected")
	}
	return err8
}

func (i *JsReqInstance) IsValidEmail(
	ctx context.Context,
	candidate string,
	options interface{},
) (EmailValidationResult, error) {
	arg0 := candidate
	arg1 := options
	memory0 := i.module.Memory()
	realloc0 := i.module.ExportedFunction("cabi_realloc")
	ptr0, len0, err0 := writeString(ctx, arg0, memory0, realloc0)
	if err0 != nil {
		var default0 EmailValidationResult
		return default0, err0
	}
	var variant11_0 uint32
	var variant11_1 uint32
	var variant11_2 uint32
	var variant11_3 uint64
	var variant11_4 uint64
	switch variantPayload := arg1.(type) {
		case AllowEmailValidationConfig:
			requireTopLevelDomain1 := variantPayload.RequireTopLevelDomain
			allowDomainLiteral1 := variantPayload.AllowDomainLiteral
			allow1 := variantPayload.Allow
			var value2 uint32
			if requireTopLevelDomain1 {
				value2 = 1
			} else {
				value2 = 0
			}
			var value3 uint32
			if allowDomainLiteral1 {
				value3 = 1
			} else {
				value3 = 0
			}
			vec5 := allow1
			len5 := uint64(len(vec5))
			result5, err5 := i.module.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len5 * 8)
			if err5 != nil {
				var default5 EmailValidationResult
				return default5, err5
			}
			ptr5 := result5[0]
			for idx := uint64(0); idx < len5; idx++ {
				e := vec5[idx]
				base := uint32(ptr5 + uint64(idx) * uint64(8))
				memory4 := i.module.Memory()
				realloc4 := i.module.ExportedFunction("cabi_realloc")
				ptr4, len4, err4 := writeString(ctx, e, memory4, realloc4)
				if err4 != nil {
					var default4 EmailValidationResult
					return default4, err4
				}
				i.module.Memory().WriteUint32Le(base+4, uint32(len4))
				i.module.Memory().WriteUint32Le(base+0, uint32(ptr4))
			}
			variant11_0 = 0
			variant11_1 = value2
			variant11_2 = value3
			variant11_3 = ptr5
			variant11_4 = len5
		case DenyEmailValidationConfig:
			requireTopLevelDomain6 := variantPayload.RequireTopLevelDomain
			allowDomainLiteral6 := variantPayload.AllowDomainLiteral
			deny6 := variantPayload.Deny
			var value7 uint32
			if requireTopLevelDomain6 {
				value7 = 1
			} else {
				value7 = 0
			}
			var value8 uint32
			if allowDomainLiteral6 {
				value8 = 1
			} else {
				value8 = 0
			}
			vec10 := deny6
			len10 := uint64(len(vec10))
			result10, err10 := i.module.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len10 * 8)
			if err10 != nil {
				var default10 EmailValidationResult
				return default10, err10
			}
			ptr10 := result10[0]
			for idx := uint64(0); idx < len10; idx++ {
				e := vec10[idx]
				base := uint32(ptr10 + uint64(idx) * uint64(8))
				memory9 := i.module.Memory()
				realloc9 := i.module.ExportedFunction("cabi_realloc")
				ptr9, len9, err9 := writeString(ctx, e, memory9, realloc9)
				if err9 != nil {
					var default9 EmailValidationResult
					return default9, err9
				}
				i.module.Memory().WriteUint32Le(base+4, uint32(len9))
				i.module.Memory().WriteUint32Le(base+0, uint32(ptr9))
			}
			variant11_0 = 1
			variant11_1 = value7
			variant11_2 = value8
			variant11_3 = ptr10
			variant11_4 = len10
		default:
			var default11 EmailValidationResult
			return default11, errors.New("invalid variant type provided")
	}
	raw12, err12 := i.module.ExportedFunction("is-valid-email").Call(ctx, uint64(ptr0), uint64(len0), uint64(variant11_0), uint64(variant11_1), uint64(variant11_2), uint64(variant11_3), uint64(variant11_4))
	if err12 != nil {
		var default12 EmailValidationResult
		return default12, err12
	}

	// The cleanup via `cabi_post_*` cleans up the memory in the guest. By
	// deferring this, we ensure that no memory is corrupted before the function
	// is done accessing it.
	defer func() {
		if postFn := i.module.ExportedFunction("cabi_post_is-valid-email"); postFn != nil {
			if _, err := postFn.Call(ctx, raw12...); err != nil {
				// If we get an error during cleanup, something really bad is
				// going on, so we panic. Also, you can't return the error from
				// the `defer`
				panic(errors.New("failed to cleanup"))
			}
		}
	}()

	results12 := raw12[0]
	value13, ok13 := i.module.Memory().ReadByte(uint32(results12 + 0))
	if !ok13 {
		var default13 EmailValidationResult
		return default13, errors.New("failed to read byte from memory")
	}
	var value26 EmailValidationResult
	var err26 error
	switch value13 {
	case 0:
		value14, ok14 := i.module.Memory().ReadByte(uint32(results12 + 4))
		if !ok14 {
			var default14 EmailValidationResult
			return default14, errors.New("failed to read byte from memory")
		}
		var enum15 EmailValidity
		switch value14 {
		case 0:
			enum15 = Valid
		case 1:
			enum15 = Invalid
		default:
			var default0 EmailValidationResult
			return default0, errors.New("invalid email-validity discriminant")
		}
		ptr16, ok16 := i.module.Memory().ReadUint32Le(uint32(results12 + 8))
		if !ok16 {
			var default16 EmailValidationResult
			return default16, errors.New("failed to read pointer from memory")
		}
		len17, ok17 := i.module.Memory().ReadUint32Le(uint32(results12 + 12))
		if !ok17 {
			var default17 EmailValidationResult
			return default17, errors.New("failed to read length from memory")
		}
		base21 := ptr16
		len21 := len17
		result21 := make([]string, len21)
		for idx21 := uint32(0); idx21 < len21; idx21++ {
			base := base21 + idx21 * 8
			ptr18, ok18 := i.module.Memory().ReadUint32Le(uint32(base + 0))
			if !ok18 {
				var default18 EmailValidationResult
				return default18, errors.New("failed to read pointer from memory")
			}
			len19, ok19 := i.module.Memory().ReadUint32Le(uint32(base + 4))
			if !ok19 {
				var default19 EmailValidationResult
				return default19, errors.New("failed to read length from memory")
			}
			buf20, ok20 := i.module.Memory().Read(ptr18, len19)
			if !ok20 {
				var default20 EmailValidationResult
				return default20, errors.New("failed to read bytes from memory")
			}
			str20 := string(buf20)
			result21[idx21] = str20
		}
		value22 := EmailValidationResult{
			Validity: enum15,
			Blocked: result21,
		}
		value26 = value22
	case 1:
		ptr23, ok23 := i.module.Memory().ReadUint32Le(uint32(results12 + 4))
		if !ok23 {
			var default23 EmailValidationResult
			return default23, errors.New("failed to read pointer from memory")
		}
		len24, ok24 := i.module.Memory().ReadUint32Le(uint32(results12 + 8))
		if !ok24 {
			var default24 EmailValidationResult
			return default24, errors.New("failed to read length from memory")
		}
		buf25, ok25 := i.module.Memory().Read(ptr23, len24)
		if !ok25 {
			var default25 EmailValidationResult
			return default25, errors.New("failed to read bytes from memory")
		}
		str25 := string(buf25)
		err26 = errors.New(str25)
	default:
		err26 = errors.New("invalid variant discriminant for expected")
	}
	return value26, err26
}

func (i *JsReqInstance) DetectSensitiveInfo(
	ctx context.Context,
	content string,
	options SensitiveInfoConfig,
) SensitiveInfoResult {
	arg0 := content
	arg1 := options
	memory0 := i.module.Memory()
	realloc0 := i.module.ExportedFunction("cabi_realloc")
	ptr0, len0, err0 := writeString(ctx, arg0, memory0, realloc0)
	// The return type doesn't contain an error so we panic if one is encountered
	if err0 != nil {
		panic(err0)
	}
	entities1 := arg1.Entities
	contextWindowSize1 := arg1.ContextWindowSize
	skipCustomDetect1 := arg1.SkipCustomDetect
	var variant8_0 uint32
	var variant8_1 uint64
	var variant8_2 uint64
	switch case8 := entities1.(type) {
		case SensitiveInfoEntitiesAllow:
			variantPayload := case8.Value
			vec4 := variantPayload
			len4 := uint64(len(vec4))
			result4, err4 := i.module.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len4 * 12)
			// The return type doesn't contain an error so we panic if one is encountered
			if err4 != nil {
				panic(err4)
			}
			ptr4 := result4[0]
			for idx := uint64(0); idx < len4; idx++ {
				e := vec4[idx]
				base := uint32(ptr4 + uint64(idx) * uint64(12))
				switch case3 := e.(type) {
					case SensitiveInfoEntityEmail:
						_ = case3
						i.module.Memory().WriteByte(base+0, 0)
					case SensitiveInfoEntityPhoneNumber:
						_ = case3
						i.module.Memory().WriteByte(base+0, 1)
					case SensitiveInfoEntityIpAddress:
						_ = case3
						i.module.Memory().WriteByte(base+0, 2)
					case SensitiveInfoEntityCreditCardNumber:
						_ = case3
						i.module.Memory().WriteByte(base+0, 3)
					case SensitiveInfoEntityCustom:
						variantPayload := case3.Value
						i.module.Memory().WriteByte(base+0, 4)
						memory2 := i.module.Memory()
						realloc2 := i.module.ExportedFunction("cabi_realloc")
						ptr2, len2, err2 := writeString(ctx, variantPayload, memory2, realloc2)
						// The return type doesn't contain an error so we panic if one is encountered
						if err2 != nil {
							panic(err2)
						}
						i.module.Memory().WriteUint32Le(base+8, uint32(len2))
						i.module.Memory().WriteUint32Le(base+4, uint32(ptr2))
					default:
						// The return type doesn't contain an error so we panic if one is encountered
						panic(errors.New("invalid variant type provided"))
				}
			}
			variant8_0 = 0
			variant8_1 = ptr4
			variant8_2 = len4
		case SensitiveInfoEntitiesDeny:
			variantPayload := case8.Value
			vec7 := variantPayload
			len7 := uint64(len(vec7))
			result7, err7 := i.module.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len7 * 12)
			// The return type doesn't contain an error so we panic if one is encountered
			if err7 != nil {
				panic(err7)
			}
			ptr7 := result7[0]
			for idx := uint64(0); idx < len7; idx++ {
				e := vec7[idx]
				base := uint32(ptr7 + uint64(idx) * uint64(12))
				switch case6 := e.(type) {
					case SensitiveInfoEntityEmail:
						_ = case6
						i.module.Memory().WriteByte(base+0, 0)
					case SensitiveInfoEntityPhoneNumber:
						_ = case6
						i.module.Memory().WriteByte(base+0, 1)
					case SensitiveInfoEntityIpAddress:
						_ = case6
						i.module.Memory().WriteByte(base+0, 2)
					case SensitiveInfoEntityCreditCardNumber:
						_ = case6
						i.module.Memory().WriteByte(base+0, 3)
					case SensitiveInfoEntityCustom:
						variantPayload := case6.Value
						i.module.Memory().WriteByte(base+0, 4)
						memory5 := i.module.Memory()
						realloc5 := i.module.ExportedFunction("cabi_realloc")
						ptr5, len5, err5 := writeString(ctx, variantPayload, memory5, realloc5)
						// The return type doesn't contain an error so we panic if one is encountered
						if err5 != nil {
							panic(err5)
						}
						i.module.Memory().WriteUint32Le(base+8, uint32(len5))
						i.module.Memory().WriteUint32Le(base+4, uint32(ptr5))
					default:
						// The return type doesn't contain an error so we panic if one is encountered
						panic(errors.New("invalid variant type provided"))
				}
			}
			variant8_0 = 1
			variant8_1 = ptr7
			variant8_2 = len7
		default:
			// The return type doesn't contain an error so we panic if one is encountered
			panic(errors.New("invalid variant type provided"))
	}
	var variant10_0 uint32
	var variant10_1 uint32
	if contextWindowSize1 == nil {
		variant10_0 = 0
		variant10_1 = 0
	} else {
		variantPayload := *contextWindowSize1
		result9 := uint32(variantPayload)
		variant10_0 = 1
		variant10_1 = result9
	}
	var value11 uint32
	if skipCustomDetect1 {
		value11 = 1
	} else {
		value11 = 0
	}
	raw12, err12 := i.module.ExportedFunction("detect-sensitive-info").Call(ctx, uint64(ptr0), uint64(len0), uint64(variant8_0), uint64(variant8_1), uint64(variant8_2), uint64(variant10_0), uint64(variant10_1), uint64(value11))
	// The return type doesn't contain an error so we panic if one is encountered
	if err12 != nil {
		panic(err12)
	}

	// The cleanup via `cabi_post_*` cleans up the memory in the guest. By
	// deferring this, we ensure that no memory is corrupted before the function
	// is done accessing it.
	defer func() {
		if postFn := i.module.ExportedFunction("cabi_post_detect-sensitive-info"); postFn != nil {
			if _, err := postFn.Call(ctx, raw12...); err != nil {
				// If we get an error during cleanup, something really bad is
				// going on, so we panic. Also, you can't return the error from
				// the `defer`
				panic(errors.New("failed to cleanup"))
			}
		}
	}()

	results12 := raw12[0]
	ptr13, ok13 := i.module.Memory().ReadUint32Le(uint32(results12 + 0))
	// The return type doesn't contain an error so we panic if one is encountered
	if !ok13 {
		panic(errors.New("failed to read pointer from memory"))
	}
	len14, ok14 := i.module.Memory().ReadUint32Le(uint32(results12 + 4))
	// The return type doesn't contain an error so we panic if one is encountered
	if !ok14 {
		panic(errors.New("failed to read length from memory"))
	}
	base25 := ptr13
	len25 := len14
	result25 := make([]DetectedSensitiveInfoEntity, len25)
	for idx25 := uint32(0); idx25 < len25; idx25++ {
		base := base25 + idx25 * 20
		value15, ok15 := i.module.Memory().ReadUint32Le(uint32(base + 0))
		// The return type doesn't contain an error so we panic if one is encountered
		if !ok15 {
			panic(errors.New("failed to read i32 from memory"))
		}
		result16 := uint32(value15)
		value17, ok17 := i.module.Memory().ReadUint32Le(uint32(base + 4))
		// The return type doesn't contain an error so we panic if one is encountered
		if !ok17 {
			panic(errors.New("failed to read i32 from memory"))
		}
		result18 := uint32(value17)
		value19, ok19 := i.module.Memory().ReadByte(uint32(base + 8))
		// The return type doesn't contain an error so we panic if one is encountered
		if !ok19 {
			panic(errors.New("failed to read byte from memory"))
		}
		var value23 SensitiveInfoEntity
		switch value19 {
		case 0:
			value23 = SensitiveInfoEntityEmail{}
		case 1:
			value23 = SensitiveInfoEntityPhoneNumber{}
		case 2:
			value23 = SensitiveInfoEntityIpAddress{}
		case 3:
			value23 = SensitiveInfoEntityCreditCardNumber{}
		case 4:
			ptr20, ok20 := i.module.Memory().ReadUint32Le(uint32(base + 12))
			// The return type doesn't contain an error so we panic if one is encountered
			if !ok20 {
				panic(errors.New("failed to read pointer from memory"))
			}
			len21, ok21 := i.module.Memory().ReadUint32Le(uint32(base + 16))
			// The return type doesn't contain an error so we panic if one is encountered
			if !ok21 {
				panic(errors.New("failed to read length from memory"))
			}
			buf22, ok22 := i.module.Memory().Read(ptr20, len21)
			// The return type doesn't contain an error so we panic if one is encountered
			if !ok22 {
				panic(errors.New("failed to read bytes from memory"))
			}
			str22 := string(buf22)
			value23 = SensitiveInfoEntityCustom{Value: str22}
		default:
			// The return type doesn't contain an error so we panic if one is encountered
			panic(errors.New("invalid sensitive-info-entity discriminant"))
		}
		value24 := DetectedSensitiveInfoEntity{
			Start: result16,
			End: result18,
			IdentifiedType: value23,
		}
		result25[idx25] = value24
	}
	ptr26, ok26 := i.module.Memory().ReadUint32Le(uint32(results12 + 8))
	// The return type doesn't contain an error so we panic if one is encountered
	if !ok26 {
		panic(errors.New("failed to read pointer from memory"))
	}
	len27, ok27 := i.module.Memory().ReadUint32Le(uint32(results12 + 12))
	// The return type doesn't contain an error so we panic if one is encountered
	if !ok27 {
		panic(errors.New("failed to read length from memory"))
	}
	base38 := ptr26
	len38 := len27
	result38 := make([]DetectedSensitiveInfoEntity, len38)
	for idx38 := uint32(0); idx38 < len38; idx38++ {
		base := base38 + idx38 * 20
		value28, ok28 := i.module.Memory().ReadUint32Le(uint32(base + 0))
		// The return type doesn't contain an error so we panic if one is encountered
		if !ok28 {
			panic(errors.New("failed to read i32 from memory"))
		}
		result29 := uint32(value28)
		value30, ok30 := i.module.Memory().ReadUint32Le(uint32(base + 4))
		// The return type doesn't contain an error so we panic if one is encountered
		if !ok30 {
			panic(errors.New("failed to read i32 from memory"))
		}
		result31 := uint32(value30)
		value32, ok32 := i.module.Memory().ReadByte(uint32(base + 8))
		// The return type doesn't contain an error so we panic if one is encountered
		if !ok32 {
			panic(errors.New("failed to read byte from memory"))
		}
		var value36 SensitiveInfoEntity
		switch value32 {
		case 0:
			value36 = SensitiveInfoEntityEmail{}
		case 1:
			value36 = SensitiveInfoEntityPhoneNumber{}
		case 2:
			value36 = SensitiveInfoEntityIpAddress{}
		case 3:
			value36 = SensitiveInfoEntityCreditCardNumber{}
		case 4:
			ptr33, ok33 := i.module.Memory().ReadUint32Le(uint32(base + 12))
			// The return type doesn't contain an error so we panic if one is encountered
			if !ok33 {
				panic(errors.New("failed to read pointer from memory"))
			}
			len34, ok34 := i.module.Memory().ReadUint32Le(uint32(base + 16))
			// The return type doesn't contain an error so we panic if one is encountered
			if !ok34 {
				panic(errors.New("failed to read length from memory"))
			}
			buf35, ok35 := i.module.Memory().Read(ptr33, len34)
			// The return type doesn't contain an error so we panic if one is encountered
			if !ok35 {
				panic(errors.New("failed to read bytes from memory"))
			}
			str35 := string(buf35)
			value36 = SensitiveInfoEntityCustom{Value: str35}
		default:
			// The return type doesn't contain an error so we panic if one is encountered
			panic(errors.New("invalid sensitive-info-entity discriminant"))
		}
		value37 := DetectedSensitiveInfoEntity{
			Start: result29,
			End: result31,
			IdentifiedType: value36,
		}
		result38[idx38] = value37
	}
	value39 := SensitiveInfoResult{
		Allowed: result25,
		Denied: result38,
	}
	return value39
}
