// Code generated by arcjet-gravity; DO NOT EDIT.

package bot

import "context"
import "errors"
import "github.com/tetratelabs/wazero"
import "github.com/tetratelabs/wazero/api"

import _ "embed"

//go:embed bot.wasm
var wasmFileBot []byte

type IBotBotIdentifier interface {
	Detect(
		ctx context.Context,
		request string,
	) (string, bool)
}

type IBotVerifyBot interface {
	Verify(
		ctx context.Context,
		botId string,
		ip string,
	) ValidatorResponse
}

type ValidatorResponse interface {
	isValidatorResponse()
}

type validatorResponse int

func (validatorResponse) isValidatorResponse() {}

const (
	Verified     validatorResponse = iota
	Spoofed      validatorResponse = iota
	Unverifiable validatorResponse = iota
)

type BotEntity = string

type AllowedBotConfig struct {
	Entities         []BotEntity
	SkipCustomDetect bool
}

type DeniedBotConfig struct {
	Entities         []BotEntity
	SkipCustomDetect bool
}

type BotResult struct {
	Allowed  []BotEntity
	Denied   []BotEntity
	Verified bool
	Spoofed  bool
}

type BotFactory struct {
	runtime wazero.Runtime
	module  wazero.CompiledModule
}

func NewBotFactory(
	ctx context.Context,
	botIdentifier IBotBotIdentifier,
	verifyBot IBotVerifyBot,
) (*BotFactory, error) {
	wazeroRuntime := wazero.NewRuntime(ctx)

	_, err0 := wazeroRuntime.NewHostModuleBuilder("arcjet:bot/bot-identifier").
		NewFunctionBuilder().
		WithFunc(func(
			ctx context.Context,
			mod api.Module,
			arg0 uint32,
			arg1 uint32,
			arg2 uint32,
		) {
			buf0, ok0 := mod.Memory().Read(arg0, arg1)
			if !ok0 {
				panic(errors.New("failed to read bytes from memory"))
			}
			str0 := string(buf0)
			value1, ok1 := botIdentifier.Detect(ctx, str0)
			if ok1 {
				variantPayload := value1
				mod.Memory().WriteByte(arg2+0, 1)
				memory2 := mod.Memory()
				realloc2 := mod.ExportedFunction("cabi_realloc")
				ptr2, len2, err2 := writeString(ctx, variantPayload, memory2, realloc2)
				if err2 != nil {
					panic(err2)
				}
				mod.Memory().WriteUint32Le(arg2+8, uint32(len2))
				mod.Memory().WriteUint32Le(arg2+4, uint32(ptr2))
			} else {
				mod.Memory().WriteByte(arg2+0, 0)
			}
		}).
		Export("detect").
		Instantiate(ctx)
	if err0 != nil {
		return nil, err0
	}
	_, err1 := wazeroRuntime.NewHostModuleBuilder("arcjet:bot/verify-bot").
		NewFunctionBuilder().
		WithFunc(func(
			ctx context.Context,
			mod api.Module,
			arg0 uint32,
			arg1 uint32,
			arg2 uint32,
			arg3 uint32,
		) uint32 {
			buf0, ok0 := mod.Memory().Read(arg0, arg1)
			if !ok0 {
				panic(errors.New("failed to read bytes from memory"))
			}
			str0 := string(buf0)
			buf1, ok1 := mod.Memory().Read(arg2, arg3)
			if !ok1 {
				panic(errors.New("failed to read bytes from memory"))
			}
			str1 := string(buf1)
			value2 := verifyBot.Verify(ctx, str0, str1)
			var enum3 uint32
			switch value2 {
			case Verified:
				enum3 = 0
			case Spoofed:
				enum3 = 1
			case Unverifiable:
				enum3 = 2
			default:
				panic(errors.New("invalid enum type provided"))
			}
			return enum3
		}).
		Export("verify").
		Instantiate(ctx)
	if err1 != nil {
		return nil, err1
	}

	// Compiling the module takes a LONG time, so we want to do it once and hold
	// onto it with the Runtime
	module, err := wazeroRuntime.CompileModule(ctx, wasmFileBot)
	if err != nil {
		return nil, err
	}
	return &BotFactory{
		runtime: wazeroRuntime,
		module:  module,
	}, nil
}

func (f *BotFactory) Instantiate(ctx context.Context) (*BotInstance, error) {
	if module, err := f.runtime.InstantiateModule(ctx, f.module, wazero.NewModuleConfig()); err != nil {
		return nil, err
	} else {
		return &BotInstance{module}, nil
	}
}

func (f *BotFactory) Close(ctx context.Context) {
	f.runtime.Close(ctx)
}

type BotInstance struct {
	module api.Module
}

func (i *BotInstance) Close(ctx context.Context) error {
	if err := i.module.Close(ctx); err != nil {
		return err
	}

	return nil
}

// writeString will put a Go string into the Wasm memory following the Component
// Model calling conventions, such as allocating memory with the realloc function
func writeString(
	ctx context.Context,
	s string,
	memory api.Memory,
	realloc api.Function,
) (uint64, uint64, error) {
	if len(s) == 0 {
		return 1, 0, nil
	}

	results, err := realloc.Call(ctx, 0, 0, 1, uint64(len(s)))
	if err != nil {
		return 1, 0, err
	}
	ptr := results[0]
	ok := memory.Write(uint32(ptr), []byte(s))
	if !ok {
		return 1, 0, errors.New("failed to write string to wasm memory")
	}
	return uint64(ptr), uint64(len(s)), nil
}

func (i *BotInstance) Detect(
	ctx context.Context,
	request string,
	options interface{},
) (BotResult, error) {
	arg0 := request
	arg1 := options
	memory0 := i.module.Memory()
	realloc0 := i.module.ExportedFunction("cabi_realloc")
	ptr0, len0, err0 := writeString(ctx, arg0, memory0, realloc0)
	if err0 != nil {
		var default0 BotResult
		return default0, err0
	}
	var variant9_0 uint32
	var variant9_1 uint64
	var variant9_2 uint64
	var variant9_3 uint32
	switch variantPayload := arg1.(type) {
	case AllowedBotConfig:
		entities1 := variantPayload.Entities
		skipCustomDetect1 := variantPayload.SkipCustomDetect
		vec3 := entities1
		len3 := uint64(len(vec3))
		result3, err3 := i.module.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len3*8)
		if err3 != nil {
			var default3 BotResult
			return default3, err3
		}
		ptr3 := result3[0]
		for idx := uint64(0); idx < len3; idx++ {
			e := vec3[idx]
			base := uint32(ptr3 + uint64(idx)*uint64(8))
			memory2 := i.module.Memory()
			realloc2 := i.module.ExportedFunction("cabi_realloc")
			ptr2, len2, err2 := writeString(ctx, e, memory2, realloc2)
			if err2 != nil {
				var default2 BotResult
				return default2, err2
			}
			i.module.Memory().WriteUint32Le(base+4, uint32(len2))
			i.module.Memory().WriteUint32Le(base+0, uint32(ptr2))
		}
		var value4 uint32
		if skipCustomDetect1 {
			value4 = 1
		} else {
			value4 = 0
		}
		variant9_0 = 0
		variant9_1 = ptr3
		variant9_2 = len3
		variant9_3 = value4
	case DeniedBotConfig:
		entities5 := variantPayload.Entities
		skipCustomDetect5 := variantPayload.SkipCustomDetect
		vec7 := entities5
		len7 := uint64(len(vec7))
		result7, err7 := i.module.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len7*8)
		if err7 != nil {
			var default7 BotResult
			return default7, err7
		}
		ptr7 := result7[0]
		for idx := uint64(0); idx < len7; idx++ {
			e := vec7[idx]
			base := uint32(ptr7 + uint64(idx)*uint64(8))
			memory6 := i.module.Memory()
			realloc6 := i.module.ExportedFunction("cabi_realloc")
			ptr6, len6, err6 := writeString(ctx, e, memory6, realloc6)
			if err6 != nil {
				var default6 BotResult
				return default6, err6
			}
			i.module.Memory().WriteUint32Le(base+4, uint32(len6))
			i.module.Memory().WriteUint32Le(base+0, uint32(ptr6))
		}
		var value8 uint32
		if skipCustomDetect5 {
			value8 = 1
		} else {
			value8 = 0
		}
		variant9_0 = 1
		variant9_1 = ptr7
		variant9_2 = len7
		variant9_3 = value8
	default:
		var default9 BotResult
		return default9, errors.New("invalid variant type provided")
	}
	raw10, err10 := i.module.ExportedFunction("detect").Call(ctx, uint64(ptr0), uint64(len0), uint64(variant9_0), uint64(variant9_1), uint64(variant9_2), uint64(variant9_3))
	if err10 != nil {
		var default10 BotResult
		return default10, err10
	}

	// The cleanup via `cabi_post_*` cleans up the memory in the guest. By
	// deferring this, we ensure that no memory is corrupted before the function
	// is done accessing it.
	defer func() {
		if postFn := i.module.ExportedFunction("cabi_post_detect"); postFn != nil {
			if _, err := postFn.Call(ctx, raw10...); err != nil {
				// If we get an error during cleanup, something really bad is
				// going on, so we panic. Also, you can't return the error from
				// the `defer`
				panic(errors.New("failed to cleanup"))
			}
		}
	}()

	results10 := raw10[0]
	value11, ok11 := i.module.Memory().ReadByte(uint32(results10 + 0))
	if !ok11 {
		var default11 BotResult
		return default11, errors.New("failed to read byte from memory")
	}
	var value32 BotResult
	var err32 error
	switch value11 {
	case 0:
		ptr12, ok12 := i.module.Memory().ReadUint32Le(uint32(results10 + 4))
		if !ok12 {
			var default12 BotResult
			return default12, errors.New("failed to read pointer from memory")
		}
		len13, ok13 := i.module.Memory().ReadUint32Le(uint32(results10 + 8))
		if !ok13 {
			var default13 BotResult
			return default13, errors.New("failed to read length from memory")
		}
		base17 := ptr12
		len17 := len13
		result17 := make([]BotEntity, len17)
		for idx17 := uint32(0); idx17 < len17; idx17++ {
			base := base17 + idx17*8
			ptr14, ok14 := i.module.Memory().ReadUint32Le(uint32(base + 0))
			if !ok14 {
				var default14 BotResult
				return default14, errors.New("failed to read pointer from memory")
			}
			len15, ok15 := i.module.Memory().ReadUint32Le(uint32(base + 4))
			if !ok15 {
				var default15 BotResult
				return default15, errors.New("failed to read length from memory")
			}
			buf16, ok16 := i.module.Memory().Read(ptr14, len15)
			if !ok16 {
				var default16 BotResult
				return default16, errors.New("failed to read bytes from memory")
			}
			str16 := string(buf16)
			result17[idx17] = str16
		}
		ptr18, ok18 := i.module.Memory().ReadUint32Le(uint32(results10 + 12))
		if !ok18 {
			var default18 BotResult
			return default18, errors.New("failed to read pointer from memory")
		}
		len19, ok19 := i.module.Memory().ReadUint32Le(uint32(results10 + 16))
		if !ok19 {
			var default19 BotResult
			return default19, errors.New("failed to read length from memory")
		}
		base23 := ptr18
		len23 := len19
		result23 := make([]BotEntity, len23)
		for idx23 := uint32(0); idx23 < len23; idx23++ {
			base := base23 + idx23*8
			ptr20, ok20 := i.module.Memory().ReadUint32Le(uint32(base + 0))
			if !ok20 {
				var default20 BotResult
				return default20, errors.New("failed to read pointer from memory")
			}
			len21, ok21 := i.module.Memory().ReadUint32Le(uint32(base + 4))
			if !ok21 {
				var default21 BotResult
				return default21, errors.New("failed to read length from memory")
			}
			buf22, ok22 := i.module.Memory().Read(ptr20, len21)
			if !ok22 {
				var default22 BotResult
				return default22, errors.New("failed to read bytes from memory")
			}
			str22 := string(buf22)
			result23[idx23] = str22
		}
		value24, ok24 := i.module.Memory().ReadByte(uint32(results10 + 20))
		if !ok24 {
			var default24 BotResult
			return default24, errors.New("failed to read byte from memory")
		}
		value25 := value24 != 0
		value26, ok26 := i.module.Memory().ReadByte(uint32(results10 + 21))
		if !ok26 {
			var default26 BotResult
			return default26, errors.New("failed to read byte from memory")
		}
		value27 := value26 != 0
		value28 := BotResult{
			Allowed:  result17,
			Denied:   result23,
			Verified: value25,
			Spoofed:  value27,
		}
		value32 = value28
	case 1:
		ptr29, ok29 := i.module.Memory().ReadUint32Le(uint32(results10 + 4))
		if !ok29 {
			var default29 BotResult
			return default29, errors.New("failed to read pointer from memory")
		}
		len30, ok30 := i.module.Memory().ReadUint32Le(uint32(results10 + 8))
		if !ok30 {
			var default30 BotResult
			return default30, errors.New("failed to read length from memory")
		}
		buf31, ok31 := i.module.Memory().Read(ptr29, len30)
		if !ok31 {
			var default31 BotResult
			return default31, errors.New("failed to read bytes from memory")
		}
		str31 := string(buf31)
		err32 = errors.New(str31)
	default:
		err32 = errors.New("invalid variant discriminant for expected")
	}
	return value32, err32
}
