// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/decide/v1alpha1/decide.proto

package decidev1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/arcjet/arcjet-go/internal/proto/decide/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DecideServiceName is the fully-qualified name of the DecideService service.
	DecideServiceName = "proto.decide.v1alpha1.DecideService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DecideServiceDecideProcedure is the fully-qualified name of the DecideService's Decide RPC.
	DecideServiceDecideProcedure = "/proto.decide.v1alpha1.DecideService/Decide"
	// DecideServiceReportProcedure is the fully-qualified name of the DecideService's Report RPC.
	DecideServiceReportProcedure = "/proto.decide.v1alpha1.DecideService/Report"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	decideServiceServiceDescriptor      = v1alpha1.File_proto_decide_v1alpha1_decide_proto.Services().ByName("DecideService")
	decideServiceDecideMethodDescriptor = decideServiceServiceDescriptor.Methods().ByName("Decide")
	decideServiceReportMethodDescriptor = decideServiceServiceDescriptor.Methods().ByName("Report")
)

// DecideServiceClient is a client for the proto.decide.v1alpha1.DecideService service.
type DecideServiceClient interface {
	Decide(context.Context, *connect.Request[v1alpha1.DecideRequest]) (*connect.Response[v1alpha1.DecideResponse], error)
	Report(context.Context, *connect.Request[v1alpha1.ReportRequest]) (*connect.Response[v1alpha1.ReportResponse], error)
}

// NewDecideServiceClient constructs a client for the proto.decide.v1alpha1.DecideService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDecideServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DecideServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &decideServiceClient{
		decide: connect.NewClient[v1alpha1.DecideRequest, v1alpha1.DecideResponse](
			httpClient,
			baseURL+DecideServiceDecideProcedure,
			connect.WithSchema(decideServiceDecideMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		report: connect.NewClient[v1alpha1.ReportRequest, v1alpha1.ReportResponse](
			httpClient,
			baseURL+DecideServiceReportProcedure,
			connect.WithSchema(decideServiceReportMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// decideServiceClient implements DecideServiceClient.
type decideServiceClient struct {
	decide *connect.Client[v1alpha1.DecideRequest, v1alpha1.DecideResponse]
	report *connect.Client[v1alpha1.ReportRequest, v1alpha1.ReportResponse]
}

// Decide calls proto.decide.v1alpha1.DecideService.Decide.
func (c *decideServiceClient) Decide(ctx context.Context, req *connect.Request[v1alpha1.DecideRequest]) (*connect.Response[v1alpha1.DecideResponse], error) {
	return c.decide.CallUnary(ctx, req)
}

// Report calls proto.decide.v1alpha1.DecideService.Report.
func (c *decideServiceClient) Report(ctx context.Context, req *connect.Request[v1alpha1.ReportRequest]) (*connect.Response[v1alpha1.ReportResponse], error) {
	return c.report.CallUnary(ctx, req)
}

// DecideServiceHandler is an implementation of the proto.decide.v1alpha1.DecideService service.
type DecideServiceHandler interface {
	Decide(context.Context, *connect.Request[v1alpha1.DecideRequest]) (*connect.Response[v1alpha1.DecideResponse], error)
	Report(context.Context, *connect.Request[v1alpha1.ReportRequest]) (*connect.Response[v1alpha1.ReportResponse], error)
}

// NewDecideServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDecideServiceHandler(svc DecideServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	decideServiceDecideHandler := connect.NewUnaryHandler(
		DecideServiceDecideProcedure,
		svc.Decide,
		connect.WithSchema(decideServiceDecideMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	decideServiceReportHandler := connect.NewUnaryHandler(
		DecideServiceReportProcedure,
		svc.Report,
		connect.WithSchema(decideServiceReportMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/proto.decide.v1alpha1.DecideService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DecideServiceDecideProcedure:
			decideServiceDecideHandler.ServeHTTP(w, r)
		case DecideServiceReportProcedure:
			decideServiceReportHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDecideServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDecideServiceHandler struct{}

func (UnimplementedDecideServiceHandler) Decide(context.Context, *connect.Request[v1alpha1.DecideRequest]) (*connect.Response[v1alpha1.DecideResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.decide.v1alpha1.DecideService.Decide is not implemented"))
}

func (UnimplementedDecideServiceHandler) Report(context.Context, *connect.Request[v1alpha1.ReportRequest]) (*connect.Response[v1alpha1.ReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.decide.v1alpha1.DecideService.Report is not implemented"))
}
