// This file is hand-maintained. It is NOT generated by protoc-gen-connect-go.
//
// The vendored decide proto is namespaced (arcjet.sdk.decide.v1alpha1) with a
// distinct descriptor path so its protobuf global-registry identity cannot
// collide with Arcjet's canonical decide proto when both are linked into the
// same Go binary (see arcjet/arcjet#8213 / ENG-852). Generating the Connect
// transport from the namespaced proto would emit the wrong wire route
// (/arcjet.sdk.decide.v1alpha1.DecideService/...) and bind the codec schema to
// the namespaced descriptor. The wire route is fixed by the wire contract and
// shared by every Arcjet SDK, so it is pinned here by hand against the
// canonical procedure names instead. The Connect codec marshals via each
// message's own ProtoReflect descriptor, so no schema/global registry is
// needed for these registry-free (no Any) messages.

package decidev1alpha1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"

	v1alpha1 "github.com/arcjet/arcjet-go/internal/proto/decide/v1alpha1"
)

// This is a compile-time assertion to ensure that this file and the connect
// package are compatible.
const _ = connect.IsAtLeastVersion1_13_0

// DecideServiceName is the fully-qualified name of the DecideService service.
const DecideServiceName = "proto.decide.v1alpha1.DecideService"

// These constants are the canonical, fully-qualified wire routes of the RPCs.
// They intentionally use the canonical (proto.decide.v1alpha1) package, not the
// vendored proto's namespaced package — see the file comment.
const (
	// DecideServiceDecideProcedure is the canonical route of the Decide RPC.
	DecideServiceDecideProcedure = "/proto.decide.v1alpha1.DecideService/Decide"
	// DecideServiceReportProcedure is the canonical route of the Report RPC.
	DecideServiceReportProcedure = "/proto.decide.v1alpha1.DecideService/Report"
)

// DecideServiceClient is a client for the proto.decide.v1alpha1.DecideService service.
type DecideServiceClient interface {
	Decide(context.Context, *connect.Request[v1alpha1.DecideRequest]) (*connect.Response[v1alpha1.DecideResponse], error)
	Report(context.Context, *connect.Request[v1alpha1.ReportRequest]) (*connect.Response[v1alpha1.ReportResponse], error)
}

// NewDecideServiceClient constructs a client for the proto.decide.v1alpha1.DecideService service.
//
// The URL supplied here should be the base URL for the Connect or gRPC server
// (for example, http://api.acme.com or https://acme.com/grpc).
func NewDecideServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DecideServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &decideServiceClient{
		decide: connect.NewClient[v1alpha1.DecideRequest, v1alpha1.DecideResponse](
			httpClient,
			baseURL+DecideServiceDecideProcedure,
			opts...,
		),
		report: connect.NewClient[v1alpha1.ReportRequest, v1alpha1.ReportResponse](
			httpClient,
			baseURL+DecideServiceReportProcedure,
			opts...,
		),
	}
}

// decideServiceClient implements DecideServiceClient.
type decideServiceClient struct {
	decide *connect.Client[v1alpha1.DecideRequest, v1alpha1.DecideResponse]
	report *connect.Client[v1alpha1.ReportRequest, v1alpha1.ReportResponse]
}

// Decide calls proto.decide.v1alpha1.DecideService.Decide.
func (c *decideServiceClient) Decide(ctx context.Context, req *connect.Request[v1alpha1.DecideRequest]) (*connect.Response[v1alpha1.DecideResponse], error) {
	return c.decide.CallUnary(ctx, req)
}

// Report calls proto.decide.v1alpha1.DecideService.Report.
func (c *decideServiceClient) Report(ctx context.Context, req *connect.Request[v1alpha1.ReportRequest]) (*connect.Response[v1alpha1.ReportResponse], error) {
	return c.report.CallUnary(ctx, req)
}

// DecideServiceHandler is an implementation of the proto.decide.v1alpha1.DecideService service.
type DecideServiceHandler interface {
	Decide(context.Context, *connect.Request[v1alpha1.DecideRequest]) (*connect.Response[v1alpha1.DecideResponse], error)
	Report(context.Context, *connect.Request[v1alpha1.ReportRequest]) (*connect.Response[v1alpha1.ReportResponse], error)
}

// NewDecideServiceHandler builds an HTTP handler from the service implementation.
// It returns the path on which to mount the handler and the handler itself.
func NewDecideServiceHandler(svc DecideServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	decideServiceDecideHandler := connect.NewUnaryHandler(
		DecideServiceDecideProcedure,
		svc.Decide,
		opts...,
	)
	decideServiceReportHandler := connect.NewUnaryHandler(
		DecideServiceReportProcedure,
		svc.Report,
		opts...,
	)
	return "/proto.decide.v1alpha1.DecideService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DecideServiceDecideProcedure:
			decideServiceDecideHandler.ServeHTTP(w, r)
		case DecideServiceReportProcedure:
			decideServiceReportHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDecideServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDecideServiceHandler struct{}

func (UnimplementedDecideServiceHandler) Decide(context.Context, *connect.Request[v1alpha1.DecideRequest]) (*connect.Response[v1alpha1.DecideResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.decide.v1alpha1.DecideService.Decide is not implemented"))
}

func (UnimplementedDecideServiceHandler) Report(context.Context, *connect.Request[v1alpha1.ReportRequest]) (*connect.Response[v1alpha1.ReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.decide.v1alpha1.DecideService.Report is not implemented"))
}
