// Code generated by arcjet-gravity; DO NOT EDIT.

package redact

import "context"
import "errors"
import "github.com/tetratelabs/wazero"
import "github.com/tetratelabs/wazero/api"

import _ "embed"

//go:embed redact.wasm
var wasmFileRedact []byte

type IRedactCustomRedact interface {
	DetectSensitiveInfo(
		ctx context.Context,
		tokens []string,
	) []*SensitiveInfoEntity
	RedactSensitiveInfo(
		ctx context.Context,
		entityType interface{},
		plaintext string,
	) *string
}

type SensitiveInfoEntity interface {
	isSensitiveInfoEntity()
}

type SensitiveInfoEntityEmail struct {}

func (SensitiveInfoEntityEmail) isSensitiveInfoEntity() {}

type SensitiveInfoEntityPhoneNumber struct {}

func (SensitiveInfoEntityPhoneNumber) isSensitiveInfoEntity() {}

type SensitiveInfoEntityIpAddress struct {}

func (SensitiveInfoEntityIpAddress) isSensitiveInfoEntity() {}

type SensitiveInfoEntityCreditCardNumber struct {}

func (SensitiveInfoEntityCreditCardNumber) isSensitiveInfoEntity() {}

type SensitiveInfoEntityCustom struct {
	Value string
}

func (SensitiveInfoEntityCustom) isSensitiveInfoEntity() {}

type RedactSensitiveInfoConfig struct {
	Entities *[]SensitiveInfoEntity
	ContextWindowSize *uint32
	SkipCustomDetect bool
	SkipCustomRedact bool
}

type RedactedSensitiveInfoEntity struct {
	Original string
	Redacted string
	Start uint32
	End uint32
	IdentifiedType SensitiveInfoEntity
}

type RedactFactory struct {
	runtime wazero.Runtime
	module wazero.CompiledModule
}

func NewRedactFactory(
	ctx context.Context,
	customRedact IRedactCustomRedact,
) (*RedactFactory, error) {
	wazeroRuntime := wazero.NewRuntime(ctx)

	_, err0 := wazeroRuntime.NewHostModuleBuilder("arcjet:redact/custom-redact").
	NewFunctionBuilder().
	WithFunc(func(
		ctx context.Context,
		mod api.Module,
		arg0 uint32,
		arg1 uint32,
		arg2 uint32,
	) {
		base3 := arg0
		len3 := arg1
		result3 := make([]string, len3)
		for idx3 := uint32(0); idx3 < len3; idx3++ {
			base := base3 + idx3 * 8
			ptr0, ok0 := mod.Memory().ReadUint32Le(uint32(base + 0))
			// The return type doesn't contain an error so we panic if one is encountered
			if !ok0 {
				panic(errors.New("failed to read pointer from memory"))
			}
			len1, ok1 := mod.Memory().ReadUint32Le(uint32(base + 4))
			// The return type doesn't contain an error so we panic if one is encountered
			if !ok1 {
				panic(errors.New("failed to read length from memory"))
			}
			buf2, ok2 := mod.Memory().Read(ptr0, len1)
			if !ok2 {
				panic(errors.New("failed to read bytes from memory"))
			}
			str2 := string(buf2)
			result3[idx3] = str2
		}
		value4 := customRedact.DetectSensitiveInfo(ctx, result3)
		vec8 := value4
		len8 := uint64(len(vec8))
		result8, err8 := mod.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len8 * 16)
		// The return type doesn't contain an error so we panic if one is encountered
		if err8 != nil {
			panic(err8)
		}
		ptr8 := result8[0]
		for idx := uint64(0); idx < len8; idx++ {
			e := vec8[idx]
			base := uint32(ptr8 + uint64(idx) * uint64(16))
			if e == nil {
				mod.Memory().WriteByte(base+0, 0)
			} else {
				variantPayload := *e
				mod.Memory().WriteByte(base+0, 1)
				switch case6 := variantPayload.(type) {
					case SensitiveInfoEntityEmail:
						_ = case6
						mod.Memory().WriteByte(base+4, 0)
					case SensitiveInfoEntityPhoneNumber:
						_ = case6
						mod.Memory().WriteByte(base+4, 1)
					case SensitiveInfoEntityIpAddress:
						_ = case6
						mod.Memory().WriteByte(base+4, 2)
					case SensitiveInfoEntityCreditCardNumber:
						_ = case6
						mod.Memory().WriteByte(base+4, 3)
					case SensitiveInfoEntityCustom:
						variantPayload := case6.Value
						mod.Memory().WriteByte(base+4, 4)
						memory5 := mod.Memory()
						realloc5 := mod.ExportedFunction("cabi_realloc")
						ptr5, len5, err5 := writeString(ctx, variantPayload, memory5, realloc5)
						if err5 != nil {
							panic(err5)
						}
						mod.Memory().WriteUint32Le(base+12, uint32(len5))
						mod.Memory().WriteUint32Le(base+8, uint32(ptr5))
					default:
						// The return type doesn't contain an error so we panic if one is encountered
						panic(errors.New("invalid variant type provided"))
				}
			}
		}
		mod.Memory().WriteUint32Le(arg2+4, uint32(len8))
		mod.Memory().WriteUint32Le(arg2+0, uint32(ptr8))
	}).
	Export("detect-sensitive-info").
	NewFunctionBuilder().
	WithFunc(func(
		ctx context.Context,
		mod api.Module,
		arg0 uint32,
		arg1 uint32,
		arg2 uint32,
		arg3 uint32,
		arg4 uint32,
		arg5 uint32,
	) {
		var value1 SensitiveInfoEntity
		switch arg0 {
		case 0:
			value1 = SensitiveInfoEntityEmail{}
		case 1:
			value1 = SensitiveInfoEntityPhoneNumber{}
		case 2:
			value1 = SensitiveInfoEntityIpAddress{}
		case 3:
			value1 = SensitiveInfoEntityCreditCardNumber{}
		case 4:
			buf0, ok0 := mod.Memory().Read(arg1, arg2)
			if !ok0 {
				panic(errors.New("failed to read bytes from memory"))
			}
			str0 := string(buf0)
			value1 = SensitiveInfoEntityCustom{Value: str0}
		default:
			// The return type doesn't contain an error so we panic if one is encountered
			panic(errors.New("invalid sensitive-info-entity discriminant"))
		}
		buf2, ok2 := mod.Memory().Read(arg3, arg4)
		if !ok2 {
			panic(errors.New("failed to read bytes from memory"))
		}
		str2 := string(buf2)
		value3 := customRedact.RedactSensitiveInfo(ctx, value1, str2)
		if value3 == nil {
			mod.Memory().WriteByte(arg5+0, 0)
		} else {
			variantPayload := *value3
			mod.Memory().WriteByte(arg5+0, 1)
			memory4 := mod.Memory()
			realloc4 := mod.ExportedFunction("cabi_realloc")
			ptr4, len4, err4 := writeString(ctx, variantPayload, memory4, realloc4)
			if err4 != nil {
				panic(err4)
			}
			mod.Memory().WriteUint32Le(arg5+8, uint32(len4))
			mod.Memory().WriteUint32Le(arg5+4, uint32(ptr4))
		}
	}).
	Export("redact-sensitive-info").
	Instantiate(ctx)
	if err0 != nil {
		return nil, err0
	}

	// Compiling the module takes a LONG time, so we want to do it once and hold
	// onto it with the Runtime
	module, err := wazeroRuntime.CompileModule(ctx, wasmFileRedact)
	if err != nil {
		return nil, err
	}
	return &RedactFactory{
		runtime: wazeroRuntime,
		module: module,
	}, nil
}

func (f *RedactFactory) Instantiate(ctx context.Context) (*RedactInstance, error) {
	if module, err := f.runtime.InstantiateModule(ctx, f.module, wazero.NewModuleConfig()); err != nil {
		return nil, err
	} else {
		return &RedactInstance{module}, nil
	}
}

func (f *RedactFactory) Close(ctx context.Context) {
	f.runtime.Close(ctx)
}

type RedactInstance struct {
	module api.Module
}

func (i *RedactInstance) Close(ctx context.Context) error {
	if err := i.module.Close(ctx); err != nil {
		return err
	}

	return nil
}

// writeString will put a Go string into the Wasm memory following the Component
// Model calling conventions, such as allocating memory with the realloc function
func writeString(
	ctx context.Context,
	s string,
	memory api.Memory,
	realloc api.Function,
) (uint64, uint64, error) {
	if len(s) == 0 {
		return 1, 0, nil
	}

	results, err := realloc.Call(ctx, 0, 0, 1, uint64(len(s)))
	if err != nil {
		return 1, 0, err
	}
	ptr := results[0]
	ok := memory.Write(uint32(ptr), []byte(s))
	if !ok {
		return 1, 0, errors.New("failed to write string to wasm memory")
	}
	return uint64(ptr), uint64(len(s)), nil
}

func (i *RedactInstance) Redact(
	ctx context.Context,
	content string,
	options RedactSensitiveInfoConfig,
) []RedactedSensitiveInfoEntity {
	arg0 := content
	arg1 := options
	memory0 := i.module.Memory()
	realloc0 := i.module.ExportedFunction("cabi_realloc")
	ptr0, len0, err0 := writeString(ctx, arg0, memory0, realloc0)
	// The return type doesn't contain an error so we panic if one is encountered
	if err0 != nil {
		panic(err0)
	}
	entities1 := arg1.Entities
	contextWindowSize1 := arg1.ContextWindowSize
	skipCustomDetect1 := arg1.SkipCustomDetect
	skipCustomRedact1 := arg1.SkipCustomRedact
	var variant5_0 uint32
	var variant5_1 uint64
	var variant5_2 uint64
	if entities1 == nil {
		variant5_0 = 0
		variant5_1 = 0
		variant5_2 = 0
	} else {
		variantPayload := *entities1
		vec4 := variantPayload
		len4 := uint64(len(vec4))
		result4, err4 := i.module.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len4 * 12)
		// The return type doesn't contain an error so we panic if one is encountered
		if err4 != nil {
			panic(err4)
		}
		ptr4 := result4[0]
		for idx := uint64(0); idx < len4; idx++ {
			e := vec4[idx]
			base := uint32(ptr4 + uint64(idx) * uint64(12))
			switch case3 := e.(type) {
				case SensitiveInfoEntityEmail:
					_ = case3
					i.module.Memory().WriteByte(base+0, 0)
				case SensitiveInfoEntityPhoneNumber:
					_ = case3
					i.module.Memory().WriteByte(base+0, 1)
				case SensitiveInfoEntityIpAddress:
					_ = case3
					i.module.Memory().WriteByte(base+0, 2)
				case SensitiveInfoEntityCreditCardNumber:
					_ = case3
					i.module.Memory().WriteByte(base+0, 3)
				case SensitiveInfoEntityCustom:
					variantPayload := case3.Value
					i.module.Memory().WriteByte(base+0, 4)
					memory2 := i.module.Memory()
					realloc2 := i.module.ExportedFunction("cabi_realloc")
					ptr2, len2, err2 := writeString(ctx, variantPayload, memory2, realloc2)
					// The return type doesn't contain an error so we panic if one is encountered
					if err2 != nil {
						panic(err2)
					}
					i.module.Memory().WriteUint32Le(base+8, uint32(len2))
					i.module.Memory().WriteUint32Le(base+4, uint32(ptr2))
				default:
					// The return type doesn't contain an error so we panic if one is encountered
					panic(errors.New("invalid variant type provided"))
			}
		}
		variant5_0 = 1
		variant5_1 = ptr4
		variant5_2 = len4
	}
	var variant7_0 uint32
	var variant7_1 uint32
	if contextWindowSize1 == nil {
		variant7_0 = 0
		variant7_1 = 0
	} else {
		variantPayload := *contextWindowSize1
		result6 := uint32(variantPayload)
		variant7_0 = 1
		variant7_1 = result6
	}
	var value8 uint32
	if skipCustomDetect1 {
		value8 = 1
	} else {
		value8 = 0
	}
	var value9 uint32
	if skipCustomRedact1 {
		value9 = 1
	} else {
		value9 = 0
	}
	raw10, err10 := i.module.ExportedFunction("redact").Call(ctx, uint64(ptr0), uint64(len0), uint64(variant5_0), uint64(variant5_1), uint64(variant5_2), uint64(variant7_0), uint64(variant7_1), uint64(value8), uint64(value9))
	// The return type doesn't contain an error so we panic if one is encountered
	if err10 != nil {
		panic(err10)
	}

	// The cleanup via `cabi_post_*` cleans up the memory in the guest. By
	// deferring this, we ensure that no memory is corrupted before the function
	// is done accessing it.
	defer func() {
		if postFn := i.module.ExportedFunction("cabi_post_redact"); postFn != nil {
			if _, err := postFn.Call(ctx, raw10...); err != nil {
				// If we get an error during cleanup, something really bad is
				// going on, so we panic. Also, you can't return the error from
				// the `defer`
				panic(errors.New("failed to cleanup"))
			}
		}
	}()

	results10 := raw10[0]
	ptr11, ok11 := i.module.Memory().ReadUint32Le(uint32(results10 + 0))
	// The return type doesn't contain an error so we panic if one is encountered
	if !ok11 {
		panic(errors.New("failed to read pointer from memory"))
	}
	len12, ok12 := i.module.Memory().ReadUint32Le(uint32(results10 + 4))
	// The return type doesn't contain an error so we panic if one is encountered
	if !ok12 {
		panic(errors.New("failed to read length from memory"))
	}
	base29 := ptr11
	len29 := len12
	result29 := make([]RedactedSensitiveInfoEntity, len29)
	for idx29 := uint32(0); idx29 < len29; idx29++ {
		base := base29 + idx29 * 36
		ptr13, ok13 := i.module.Memory().ReadUint32Le(uint32(base + 0))
		// The return type doesn't contain an error so we panic if one is encountered
		if !ok13 {
			panic(errors.New("failed to read pointer from memory"))
		}
		len14, ok14 := i.module.Memory().ReadUint32Le(uint32(base + 4))
		// The return type doesn't contain an error so we panic if one is encountered
		if !ok14 {
			panic(errors.New("failed to read length from memory"))
		}
		buf15, ok15 := i.module.Memory().Read(ptr13, len14)
		// The return type doesn't contain an error so we panic if one is encountered
		if !ok15 {
			panic(errors.New("failed to read bytes from memory"))
		}
		str15 := string(buf15)
		ptr16, ok16 := i.module.Memory().ReadUint32Le(uint32(base + 8))
		// The return type doesn't contain an error so we panic if one is encountered
		if !ok16 {
			panic(errors.New("failed to read pointer from memory"))
		}
		len17, ok17 := i.module.Memory().ReadUint32Le(uint32(base + 12))
		// The return type doesn't contain an error so we panic if one is encountered
		if !ok17 {
			panic(errors.New("failed to read length from memory"))
		}
		buf18, ok18 := i.module.Memory().Read(ptr16, len17)
		// The return type doesn't contain an error so we panic if one is encountered
		if !ok18 {
			panic(errors.New("failed to read bytes from memory"))
		}
		str18 := string(buf18)
		value19, ok19 := i.module.Memory().ReadUint32Le(uint32(base + 16))
		// The return type doesn't contain an error so we panic if one is encountered
		if !ok19 {
			panic(errors.New("failed to read i32 from memory"))
		}
		result20 := uint32(value19)
		value21, ok21 := i.module.Memory().ReadUint32Le(uint32(base + 20))
		// The return type doesn't contain an error so we panic if one is encountered
		if !ok21 {
			panic(errors.New("failed to read i32 from memory"))
		}
		result22 := uint32(value21)
		value23, ok23 := i.module.Memory().ReadByte(uint32(base + 24))
		// The return type doesn't contain an error so we panic if one is encountered
		if !ok23 {
			panic(errors.New("failed to read byte from memory"))
		}
		var value27 SensitiveInfoEntity
		switch value23 {
		case 0:
			value27 = SensitiveInfoEntityEmail{}
		case 1:
			value27 = SensitiveInfoEntityPhoneNumber{}
		case 2:
			value27 = SensitiveInfoEntityIpAddress{}
		case 3:
			value27 = SensitiveInfoEntityCreditCardNumber{}
		case 4:
			ptr24, ok24 := i.module.Memory().ReadUint32Le(uint32(base + 28))
			// The return type doesn't contain an error so we panic if one is encountered
			if !ok24 {
				panic(errors.New("failed to read pointer from memory"))
			}
			len25, ok25 := i.module.Memory().ReadUint32Le(uint32(base + 32))
			// The return type doesn't contain an error so we panic if one is encountered
			if !ok25 {
				panic(errors.New("failed to read length from memory"))
			}
			buf26, ok26 := i.module.Memory().Read(ptr24, len25)
			// The return type doesn't contain an error so we panic if one is encountered
			if !ok26 {
				panic(errors.New("failed to read bytes from memory"))
			}
			str26 := string(buf26)
			value27 = SensitiveInfoEntityCustom{Value: str26}
		default:
			// The return type doesn't contain an error so we panic if one is encountered
			panic(errors.New("invalid sensitive-info-entity discriminant"))
		}
		value28 := RedactedSensitiveInfoEntity{
			Original: str15,
			Redacted: str18,
			Start: result20,
			End: result22,
			IdentifiedType: value27,
		}
		result29[idx29] = value28
	}
	return result29
}
