// Code generated by arcjet-gravity; DO NOT EDIT.

package filter

import "context"
import "errors"
import "github.com/tetratelabs/wazero"
import "github.com/tetratelabs/wazero/api"

import _ "embed"

//go:embed filter.wasm
var wasmFileFilter []byte

type IFilterFilterOverrides interface {
	IpLookup(
		ctx context.Context,
		ip string,
	) (string, bool)
}

type FilterResult struct {
	Allowed                 bool
	MatchedExpressions      []string
	UndeterminedExpressions []string
}

type FilterFactory struct {
	runtime wazero.Runtime
	module  wazero.CompiledModule
}

func NewFilterFactory(
	ctx context.Context,
	filterOverrides IFilterFilterOverrides,
) (*FilterFactory, error) {
	wazeroRuntime := wazero.NewRuntime(ctx)

	_, err0 := wazeroRuntime.NewHostModuleBuilder("arcjet:filter/filter-overrides").
		NewFunctionBuilder().
		WithFunc(func(
			ctx context.Context,
			mod api.Module,
			arg0 uint32,
			arg1 uint32,
			arg2 uint32,
		) {
			buf0, ok0 := mod.Memory().Read(arg0, arg1)
			if !ok0 {
				panic(errors.New("failed to read bytes from memory"))
			}
			str0 := string(buf0)
			value1, ok1 := filterOverrides.IpLookup(ctx, str0)
			if ok1 {
				variantPayload := value1
				mod.Memory().WriteByte(arg2+0, 1)
				memory2 := mod.Memory()
				realloc2 := mod.ExportedFunction("cabi_realloc")
				ptr2, len2, err2 := writeString(ctx, variantPayload, memory2, realloc2)
				if err2 != nil {
					panic(err2)
				}
				mod.Memory().WriteUint32Le(arg2+8, uint32(len2))
				mod.Memory().WriteUint32Le(arg2+4, uint32(ptr2))
			} else {
				mod.Memory().WriteByte(arg2+0, 0)
			}
		}).
		Export("ip-lookup").
		Instantiate(ctx)
	if err0 != nil {
		return nil, err0
	}

	// Compiling the module takes a LONG time, so we want to do it once and hold
	// onto it with the Runtime
	module, err := wazeroRuntime.CompileModule(ctx, wasmFileFilter)
	if err != nil {
		return nil, err
	}
	return &FilterFactory{
		runtime: wazeroRuntime,
		module:  module,
	}, nil
}

func (f *FilterFactory) Instantiate(ctx context.Context) (*FilterInstance, error) {
	if module, err := f.runtime.InstantiateModule(ctx, f.module, wazero.NewModuleConfig()); err != nil {
		return nil, err
	} else {
		return &FilterInstance{module}, nil
	}
}

func (f *FilterFactory) Close(ctx context.Context) {
	f.runtime.Close(ctx)
}

type FilterInstance struct {
	module api.Module
}

func (i *FilterInstance) Close(ctx context.Context) error {
	if err := i.module.Close(ctx); err != nil {
		return err
	}

	return nil
}

// writeString will put a Go string into the Wasm memory following the Component
// Model calling conventions, such as allocating memory with the realloc function
func writeString(
	ctx context.Context,
	s string,
	memory api.Memory,
	realloc api.Function,
) (uint64, uint64, error) {
	if len(s) == 0 {
		return 1, 0, nil
	}

	results, err := realloc.Call(ctx, 0, 0, 1, uint64(len(s)))
	if err != nil {
		return 1, 0, err
	}
	ptr := results[0]
	ok := memory.Write(uint32(ptr), []byte(s))
	if !ok {
		return 1, 0, errors.New("failed to write string to wasm memory")
	}
	return uint64(ptr), uint64(len(s)), nil
}

func (i *FilterInstance) MatchFilters(
	ctx context.Context,
	request string,
	localFields string,
	expressions []string,
	allowIfMatch bool,
) (FilterResult, error) {
	arg0 := request
	arg1 := localFields
	arg2 := expressions
	arg3 := allowIfMatch
	memory0 := i.module.Memory()
	realloc0 := i.module.ExportedFunction("cabi_realloc")
	ptr0, len0, err0 := writeString(ctx, arg0, memory0, realloc0)
	if err0 != nil {
		var default0 FilterResult
		return default0, err0
	}
	memory1 := i.module.Memory()
	realloc1 := i.module.ExportedFunction("cabi_realloc")
	ptr1, len1, err1 := writeString(ctx, arg1, memory1, realloc1)
	if err1 != nil {
		var default1 FilterResult
		return default1, err1
	}
	vec3 := arg2
	len3 := uint64(len(vec3))
	result3, err3 := i.module.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len3*8)
	if err3 != nil {
		var default3 FilterResult
		return default3, err3
	}
	ptr3 := result3[0]
	for idx := uint64(0); idx < len3; idx++ {
		e := vec3[idx]
		base := uint32(ptr3 + uint64(idx)*uint64(8))
		memory2 := i.module.Memory()
		realloc2 := i.module.ExportedFunction("cabi_realloc")
		ptr2, len2, err2 := writeString(ctx, e, memory2, realloc2)
		if err2 != nil {
			var default2 FilterResult
			return default2, err2
		}
		i.module.Memory().WriteUint32Le(base+4, uint32(len2))
		i.module.Memory().WriteUint32Le(base+0, uint32(ptr2))
	}
	var value4 uint32
	if arg3 {
		value4 = 1
	} else {
		value4 = 0
	}
	raw5, err5 := i.module.ExportedFunction("match-filters").Call(ctx, uint64(ptr0), uint64(len0), uint64(ptr1), uint64(len1), uint64(ptr3), uint64(len3), uint64(value4))
	if err5 != nil {
		var default5 FilterResult
		return default5, err5
	}

	// The cleanup via `cabi_post_*` cleans up the memory in the guest. By
	// deferring this, we ensure that no memory is corrupted before the function
	// is done accessing it.
	defer func() {
		if postFn := i.module.ExportedFunction("cabi_post_match-filters"); postFn != nil {
			if _, err := postFn.Call(ctx, raw5...); err != nil {
				// If we get an error during cleanup, something really bad is
				// going on, so we panic. Also, you can't return the error from
				// the `defer`
				panic(errors.New("failed to cleanup"))
			}
		}
	}()

	results5 := raw5[0]
	value6, ok6 := i.module.Memory().ReadByte(uint32(results5 + 0))
	if !ok6 {
		var default6 FilterResult
		return default6, errors.New("failed to read byte from memory")
	}
	var value25 FilterResult
	var err25 error
	switch value6 {
	case 0:
		value7, ok7 := i.module.Memory().ReadByte(uint32(results5 + 4))
		if !ok7 {
			var default7 FilterResult
			return default7, errors.New("failed to read byte from memory")
		}
		value8 := value7 != 0
		ptr9, ok9 := i.module.Memory().ReadUint32Le(uint32(results5 + 8))
		if !ok9 {
			var default9 FilterResult
			return default9, errors.New("failed to read pointer from memory")
		}
		len10, ok10 := i.module.Memory().ReadUint32Le(uint32(results5 + 12))
		if !ok10 {
			var default10 FilterResult
			return default10, errors.New("failed to read length from memory")
		}
		base14 := ptr9
		len14 := len10
		result14 := make([]string, len14)
		for idx14 := uint32(0); idx14 < len14; idx14++ {
			base := base14 + idx14*8
			ptr11, ok11 := i.module.Memory().ReadUint32Le(uint32(base + 0))
			if !ok11 {
				var default11 FilterResult
				return default11, errors.New("failed to read pointer from memory")
			}
			len12, ok12 := i.module.Memory().ReadUint32Le(uint32(base + 4))
			if !ok12 {
				var default12 FilterResult
				return default12, errors.New("failed to read length from memory")
			}
			buf13, ok13 := i.module.Memory().Read(ptr11, len12)
			if !ok13 {
				var default13 FilterResult
				return default13, errors.New("failed to read bytes from memory")
			}
			str13 := string(buf13)
			result14[idx14] = str13
		}
		ptr15, ok15 := i.module.Memory().ReadUint32Le(uint32(results5 + 16))
		if !ok15 {
			var default15 FilterResult
			return default15, errors.New("failed to read pointer from memory")
		}
		len16, ok16 := i.module.Memory().ReadUint32Le(uint32(results5 + 20))
		if !ok16 {
			var default16 FilterResult
			return default16, errors.New("failed to read length from memory")
		}
		base20 := ptr15
		len20 := len16
		result20 := make([]string, len20)
		for idx20 := uint32(0); idx20 < len20; idx20++ {
			base := base20 + idx20*8
			ptr17, ok17 := i.module.Memory().ReadUint32Le(uint32(base + 0))
			if !ok17 {
				var default17 FilterResult
				return default17, errors.New("failed to read pointer from memory")
			}
			len18, ok18 := i.module.Memory().ReadUint32Le(uint32(base + 4))
			if !ok18 {
				var default18 FilterResult
				return default18, errors.New("failed to read length from memory")
			}
			buf19, ok19 := i.module.Memory().Read(ptr17, len18)
			if !ok19 {
				var default19 FilterResult
				return default19, errors.New("failed to read bytes from memory")
			}
			str19 := string(buf19)
			result20[idx20] = str19
		}
		value21 := FilterResult{
			Allowed:                 value8,
			MatchedExpressions:      result14,
			UndeterminedExpressions: result20,
		}
		value25 = value21
	case 1:
		ptr22, ok22 := i.module.Memory().ReadUint32Le(uint32(results5 + 4))
		if !ok22 {
			var default22 FilterResult
			return default22, errors.New("failed to read pointer from memory")
		}
		len23, ok23 := i.module.Memory().ReadUint32Le(uint32(results5 + 8))
		if !ok23 {
			var default23 FilterResult
			return default23, errors.New("failed to read length from memory")
		}
		buf24, ok24 := i.module.Memory().Read(ptr22, len23)
		if !ok24 {
			var default24 FilterResult
			return default24, errors.New("failed to read bytes from memory")
		}
		str24 := string(buf24)
		err25 = errors.New(str24)
	default:
		err25 = errors.New("invalid variant discriminant for expected")
	}
	return value25, err25
}
