// Code generated by arcjet-gravity; DO NOT EDIT.

package emailvalidator

import "context"
import "errors"
import "github.com/tetratelabs/wazero"
import "github.com/tetratelabs/wazero/api"

import _ "embed"

//go:embed email_validator.wasm
var wasmFileEmailValidator []byte

type IEmailValidatorEmailValidatorOverrides interface {
	IsFreeEmail(
		ctx context.Context,
		domain string,
	) bool
	IsDisposableEmail(
		ctx context.Context,
		domain string,
	) bool
	HasMxRecords(
		ctx context.Context,
		domain string,
	) bool
	HasGravatar(
		ctx context.Context,
		email string,
	) bool
}

type AllowEmailValidationConfig struct {
	RequireTopLevelDomain bool
	AllowDomainLiteral    bool
	Allow                 []string
}

type DenyEmailValidationConfig struct {
	RequireTopLevelDomain bool
	AllowDomainLiteral    bool
	Deny                  []string
}

type EmailValidatorFactory struct {
	runtime wazero.Runtime
	module  wazero.CompiledModule
}

func NewEmailValidatorFactory(
	ctx context.Context,
	emailValidatorOverrides IEmailValidatorEmailValidatorOverrides,
) (*EmailValidatorFactory, error) {
	wazeroRuntime := wazero.NewRuntime(ctx)

	_, err0 := wazeroRuntime.NewHostModuleBuilder("arcjet:email-validator/email-validator-overrides").
		NewFunctionBuilder().
		WithFunc(func(
			ctx context.Context,
			mod api.Module,
			arg0 uint32,
			arg1 uint32,
		) uint32 {
			buf0, ok0 := mod.Memory().Read(arg0, arg1)
			if !ok0 {
				panic(errors.New("failed to read bytes from memory"))
			}
			str0 := string(buf0)
			value1 := emailValidatorOverrides.IsFreeEmail(ctx, str0)
			var value2 uint32
			if value1 {
				value2 = 1
			} else {
				value2 = 0
			}
			return value2
		}).
		Export("is-free-email").
		NewFunctionBuilder().
		WithFunc(func(
			ctx context.Context,
			mod api.Module,
			arg0 uint32,
			arg1 uint32,
		) uint32 {
			buf0, ok0 := mod.Memory().Read(arg0, arg1)
			if !ok0 {
				panic(errors.New("failed to read bytes from memory"))
			}
			str0 := string(buf0)
			value1 := emailValidatorOverrides.IsDisposableEmail(ctx, str0)
			var value2 uint32
			if value1 {
				value2 = 1
			} else {
				value2 = 0
			}
			return value2
		}).
		Export("is-disposable-email").
		NewFunctionBuilder().
		WithFunc(func(
			ctx context.Context,
			mod api.Module,
			arg0 uint32,
			arg1 uint32,
		) uint32 {
			buf0, ok0 := mod.Memory().Read(arg0, arg1)
			if !ok0 {
				panic(errors.New("failed to read bytes from memory"))
			}
			str0 := string(buf0)
			value1 := emailValidatorOverrides.HasMxRecords(ctx, str0)
			var value2 uint32
			if value1 {
				value2 = 1
			} else {
				value2 = 0
			}
			return value2
		}).
		Export("has-mx-records").
		NewFunctionBuilder().
		WithFunc(func(
			ctx context.Context,
			mod api.Module,
			arg0 uint32,
			arg1 uint32,
		) uint32 {
			buf0, ok0 := mod.Memory().Read(arg0, arg1)
			if !ok0 {
				panic(errors.New("failed to read bytes from memory"))
			}
			str0 := string(buf0)
			value1 := emailValidatorOverrides.HasGravatar(ctx, str0)
			var value2 uint32
			if value1 {
				value2 = 1
			} else {
				value2 = 0
			}
			return value2
		}).
		Export("has-gravatar").
		Instantiate(ctx)
	if err0 != nil {
		return nil, err0
	}

	// Compiling the module takes a LONG time, so we want to do it once and hold
	// onto it with the Runtime
	module, err := wazeroRuntime.CompileModule(ctx, wasmFileEmailValidator)
	if err != nil {
		return nil, err
	}
	return &EmailValidatorFactory{
		runtime: wazeroRuntime,
		module:  module,
	}, nil
}

func (f *EmailValidatorFactory) Instantiate(ctx context.Context) (*EmailValidatorInstance, error) {
	if module, err := f.runtime.InstantiateModule(ctx, f.module, wazero.NewModuleConfig()); err != nil {
		return nil, err
	} else {
		return &EmailValidatorInstance{module}, nil
	}
}

func (f *EmailValidatorFactory) Close(ctx context.Context) {
	f.runtime.Close(ctx)
}

type EmailValidatorInstance struct {
	module api.Module
}

func (i *EmailValidatorInstance) Close(ctx context.Context) error {
	if err := i.module.Close(ctx); err != nil {
		return err
	}

	return nil
}

// writeString will put a Go string into the Wasm memory following the Component
// Model calling conventions, such as allocating memory with the realloc function
func writeString(
	ctx context.Context,
	s string,
	memory api.Memory,
	realloc api.Function,
) (uint64, uint64, error) {
	if len(s) == 0 {
		return 1, 0, nil
	}

	results, err := realloc.Call(ctx, 0, 0, 1, uint64(len(s)))
	if err != nil {
		return 1, 0, err
	}
	ptr := results[0]
	ok := memory.Write(uint32(ptr), []byte(s))
	if !ok {
		return 1, 0, errors.New("failed to write string to wasm memory")
	}
	return uint64(ptr), uint64(len(s)), nil
}

func (i *EmailValidatorInstance) IsValidEmail(
	ctx context.Context,
	candidate string,
	options interface{},
) (string, error) {
	arg0 := candidate
	arg1 := options
	memory0 := i.module.Memory()
	realloc0 := i.module.ExportedFunction("cabi_realloc")
	ptr0, len0, err0 := writeString(ctx, arg0, memory0, realloc0)
	if err0 != nil {
		var default0 string
		return default0, err0
	}
	var variant11_0 uint32
	var variant11_1 uint32
	var variant11_2 uint32
	var variant11_3 uint64
	var variant11_4 uint64
	switch variantPayload := arg1.(type) {
	case AllowEmailValidationConfig:
		requireTopLevelDomain1 := variantPayload.RequireTopLevelDomain
		allowDomainLiteral1 := variantPayload.AllowDomainLiteral
		allow1 := variantPayload.Allow
		var value2 uint32
		if requireTopLevelDomain1 {
			value2 = 1
		} else {
			value2 = 0
		}
		var value3 uint32
		if allowDomainLiteral1 {
			value3 = 1
		} else {
			value3 = 0
		}
		vec5 := allow1
		len5 := uint64(len(vec5))
		result5, err5 := i.module.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len5*8)
		if err5 != nil {
			var default5 string
			return default5, err5
		}
		ptr5 := result5[0]
		for idx := uint64(0); idx < len5; idx++ {
			e := vec5[idx]
			base := uint32(ptr5 + uint64(idx)*uint64(8))
			memory4 := i.module.Memory()
			realloc4 := i.module.ExportedFunction("cabi_realloc")
			ptr4, len4, err4 := writeString(ctx, e, memory4, realloc4)
			if err4 != nil {
				var default4 string
				return default4, err4
			}
			i.module.Memory().WriteUint32Le(base+4, uint32(len4))
			i.module.Memory().WriteUint32Le(base+0, uint32(ptr4))
		}
		variant11_0 = 0
		variant11_1 = value2
		variant11_2 = value3
		variant11_3 = ptr5
		variant11_4 = len5
	case DenyEmailValidationConfig:
		requireTopLevelDomain6 := variantPayload.RequireTopLevelDomain
		allowDomainLiteral6 := variantPayload.AllowDomainLiteral
		deny6 := variantPayload.Deny
		var value7 uint32
		if requireTopLevelDomain6 {
			value7 = 1
		} else {
			value7 = 0
		}
		var value8 uint32
		if allowDomainLiteral6 {
			value8 = 1
		} else {
			value8 = 0
		}
		vec10 := deny6
		len10 := uint64(len(vec10))
		result10, err10 := i.module.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len10*8)
		if err10 != nil {
			var default10 string
			return default10, err10
		}
		ptr10 := result10[0]
		for idx := uint64(0); idx < len10; idx++ {
			e := vec10[idx]
			base := uint32(ptr10 + uint64(idx)*uint64(8))
			memory9 := i.module.Memory()
			realloc9 := i.module.ExportedFunction("cabi_realloc")
			ptr9, len9, err9 := writeString(ctx, e, memory9, realloc9)
			if err9 != nil {
				var default9 string
				return default9, err9
			}
			i.module.Memory().WriteUint32Le(base+4, uint32(len9))
			i.module.Memory().WriteUint32Le(base+0, uint32(ptr9))
		}
		variant11_0 = 1
		variant11_1 = value7
		variant11_2 = value8
		variant11_3 = ptr10
		variant11_4 = len10
	default:
		var default11 string
		return default11, errors.New("invalid variant type provided")
	}
	raw12, err12 := i.module.ExportedFunction("is-valid-email").Call(ctx, uint64(ptr0), uint64(len0), uint64(variant11_0), uint64(variant11_1), uint64(variant11_2), uint64(variant11_3), uint64(variant11_4))
	if err12 != nil {
		var default12 string
		return default12, err12
	}

	// The cleanup via `cabi_post_*` cleans up the memory in the guest. By
	// deferring this, we ensure that no memory is corrupted before the function
	// is done accessing it.
	defer func() {
		if postFn := i.module.ExportedFunction("cabi_post_is-valid-email"); postFn != nil {
			if _, err := postFn.Call(ctx, raw12...); err != nil {
				// If we get an error during cleanup, something really bad is
				// going on, so we panic. Also, you can't return the error from
				// the `defer`
				panic(errors.New("failed to cleanup"))
			}
		}
	}()

	results12 := raw12[0]
	value13, ok13 := i.module.Memory().ReadByte(uint32(results12 + 0))
	if !ok13 {
		var default13 string
		return default13, errors.New("failed to read byte from memory")
	}
	var value20 string
	var err20 error
	switch value13 {
	case 0:
		ptr14, ok14 := i.module.Memory().ReadUint32Le(uint32(results12 + 4))
		if !ok14 {
			var default14 string
			return default14, errors.New("failed to read pointer from memory")
		}
		len15, ok15 := i.module.Memory().ReadUint32Le(uint32(results12 + 8))
		if !ok15 {
			var default15 string
			return default15, errors.New("failed to read length from memory")
		}
		buf16, ok16 := i.module.Memory().Read(ptr14, len15)
		if !ok16 {
			var default16 string
			return default16, errors.New("failed to read bytes from memory")
		}
		str16 := string(buf16)
		value20 = str16
	case 1:
		ptr17, ok17 := i.module.Memory().ReadUint32Le(uint32(results12 + 4))
		if !ok17 {
			var default17 string
			return default17, errors.New("failed to read pointer from memory")
		}
		len18, ok18 := i.module.Memory().ReadUint32Le(uint32(results12 + 8))
		if !ok18 {
			var default18 string
			return default18, errors.New("failed to read length from memory")
		}
		buf19, ok19 := i.module.Memory().Read(ptr17, len18)
		if !ok19 {
			var default19 string
			return default19, errors.New("failed to read bytes from memory")
		}
		str19 := string(buf19)
		err20 = errors.New(str19)
	default:
		err20 = errors.New("invalid variant discriminant for expected")
	}
	return value20, err20
}
